export const SELLER_FEATURE_LABELS={
  catalogue:'Catalogue vendeur',physical_products:'Produits physiques',digital_products:'Produits numériques',dashboard:'Tableau de bord vendeur',stock:'Gestion du stock',orders:'Gestion des commandes',wallet:'Portefeuille vendeur',analytics:'Analytics / statistiques',crm:'CRM vendeur',promo_codes:'Codes promo',affiliate:'Parrainage et affiliation',advertising:'Publicité PJD',featured_listing:'Mise en avant des produits',seller_ai:'IA vendeur',marketing_automation:'Automatisation marketing',certification:'Certification boutique',team:'Gestion d’équipe',api:'API et intégrations',social_publishing:'Publication et partage vers les réseaux sociaux',priority_support:'Support prioritaire',badge:'Badge boutique'
};

export const SELLER_FEATURE_LEVELS={standard:{analytics:'basic',promo_codes:'limited',affiliate:'basic',seller_ai:'basic'},gold:{analytics:'advanced',crm:true,promo_codes:true,affiliate:true,advertising:'limited',featured_listing:'limited',seller_ai:'advanced',priority_support:true,badge:'gold'},platinum:{analytics:'pro',crm:true,promo_codes:true,affiliate:true,advertising:'advanced',featured_listing:true,seller_ai:'pro',marketing_automation:true,certification:true,team:'limited',api:'limited',social_publishing:true,priority_support:true,badge:'platinum'},diamond:{analytics:'premium',crm:true,promo_codes:true,affiliate:true,advertising:'priority',featured_listing:'priority',seller_ai:'premium',marketing_automation:'full',certification:'priority',team:true,api:'advanced',social_publishing:'priority',priority_support:'vip',badge:'diamond'}};

export function hasSellerFeature(plan,feature){const value=plan?.features?.[feature]??SELLER_FEATURE_LEVELS[plan?.code]?.[feature];return value===true||['basic','advanced','pro','premium','limited','priority','full','vip','gold','platinum','diamond'].includes(value)}
export function sellerFeatureValue(plan,feature){return plan?.features?.[feature]??SELLER_FEATURE_LEVELS[plan?.code]?.[feature]??false}
export function sellerFeatureLabel(feature){return SELLER_FEATURE_LABELS[feature]||feature}
