const crypto = require('crypto');
const env=n=>process.env[n]||'';
const dec=v=>JSON.parse(Buffer.from(v,'base64url').toString());
const verifyState=s=>{const [body,sig]=String(s||'').split('.');if(!body||!sig||!env('SOCIAL_OAUTH_STATE_SECRET'))return null;const expected=crypto.createHmac('sha256',env('SOCIAL_OAUTH_STATE_SECRET')).update(body).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;return dec(body)};
const origin=req=>env('APP_URL')||`${req.headers['x-forwarded-proto']||'https'}://${req.headers.host}`;
const json=async(r)=>{try{return await r.json()}catch{return{}}};
async function upsert(provider,user,token,refresh,expires,accountName,accountId,scopes){const base=env('VITE_SUPABASE_URL'),key=env('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw Error('SUPABASE_SERVICE_ROLE_KEY non configuré');const body={user_id:user,provider,account_name:accountName||provider,account_id:accountId||null,access_token:token,refresh_token:refresh||null,token_expires_at:expires?new Date(Date.now()+Number(expires)*1000).toISOString():null,scopes:scopes||[],status:'connected',last_error:null,updated_at:new Date().toISOString()};const r=await fetch(`${base}/rest/v1/social_connections?on_conflict=user_id,provider`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,Prefer:'resolution=merge-duplicates,return=minimal','Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(`Supabase: ${await r.text()}`)}
module.exports=async(req,res)=>{if(req.method!=='GET')return res.status(405).send('Méthode non autorisée');try{const s=verifyState(req.query?.state);if(!s)return res.status(400).send('État OAuth invalide.');const code=req.query?.code;if(!code)throw Error(req.query?.error_description||'Autorisation refusée.');const p=s.p,redirect=`${origin(req)}/api/social/oauth/callback`;let token='',refresh='',expires='',name=p,id='',scopes=[];
if(p==='facebook'||p==='instagram'||p==='whatsapp'){const r=await fetch(`https://graph.facebook.com/v23.0/oauth/access_token?client_id=${encodeURIComponent(env('META_CLIENT_ID'))}&client_secret=${encodeURIComponent(env('META_CLIENT_SECRET'))}&redirect_uri=${encodeURIComponent(redirect)}&code=${encodeURIComponent(code)}`);const j=await json(r);if(!r.ok||!j.access_token)throw Error(j.error?.message||'Échange Meta impossible');token=j.access_token;scopes=(env('META_SCOPES')||'').split(',').filter(Boolean);const me=await fetch(`https://graph.facebook.com/v23.0/me?fields=id,name&access_token=${encodeURIComponent(token)}`);const mj=await json(me);name=mj.name||p;id=mj.id||'';
}else if(p==='tiktok'){const r=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:env('TIKTOK_CLIENT_KEY'),client_secret:env('TIKTOK_CLIENT_SECRET'),code,grant_type:'authorization_code',redirect_uri:redirect})});const j=await json(r);if(!r.ok||!j.access_token)throw Error(j.error_description||'Échange TikTok impossible');token=j.access_token;refresh=j.refresh_token;expires=j.expires_in;id=j.open_id||'';name=j.open_id||'TikTok';scopes=(j.scope||'').split(',').filter(Boolean);
}else if(p==='youtube'){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:env('GOOGLE_CLIENT_ID'),client_secret:env('GOOGLE_CLIENT_SECRET'),redirect_uri:redirect,grant_type:'authorization_code'})});const j=await json(r);if(!r.ok||!j.access_token)throw Error(j.error_description||'Échange Google impossible');token=j.access_token;refresh=j.refresh_token;expires=j.expires_in;scopes=['https://www.googleapis.com/auth/youtube.upload'];const ch=await fetch('https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true',{headers:{Authorization:`Bearer ${token}`}});const cj=await json(ch);id=cj.items?.[0]?.id||'';name=cj.items?.[0]?.snippet?.title||'YouTube';
}else throw Error('Provider non supporté');
await upsert(p,s.u,token,refresh,expires,name,id,scopes);return res.redirect(302,`${origin(req)}${s.r||'/'}?social_connected=${encodeURIComponent(p)}`);
}catch(e){return res.status(400).send(`Connexion sociale impossible : ${String(e.message||e)}`)}};
