import React,{useState}from'react';
import{aiHub}from'./aiHub';

const MODES=[['general','🤖','Assistant général'],['product','📦','IA Produit'],['marketing','📣','IA Marketing'],['commercial','📊','IA Commerciale'],['seller','🛍️','Assistant vendeur'],['customer','💬','Assistant client']];
export default function AICenter({onClose}){
 const[task,setTask]=useState('general'),[input,setInput]=useState(''),[result,setResult]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const run=async()=>{if(!input.trim()||busy)return;setBusy(true);setError('');setResult('');try{const r=await aiHub(task,{request:input.trim()});setResult(typeof r==='string'?r:JSON.stringify(r,null,2))}catch(e){setError(e.message||'Impossible de contacter le Centre IA.')}finally{setBusy(false)}};
 return <div className="pjd-ai-overlay"><div className="pjd-ai-card" style={{maxWidth:980}}><div className="pjd-ai-head"><div><span className="pjd-ai-badge">CENTRE IA PJD MAKER</span><h2>Toutes vos IA au même endroit</h2><p>Produit, marketing, commercial, vendeur et client — sans connexion aux réseaux sociaux.</p></div><button onClick={onClose}>✕</button></div><div style={{display:'grid',gridTemplateColumns:'240px 1fr',gap:18}}><nav style={{display:'grid',gap:8,alignContent:'start'}}>{MODES.map(([id,icon,label])=><button key={id} onClick={()=>{setTask(id);setResult('');setError('')}} style={{padding:12,textAlign:'left',borderRadius:10,border:task===id?'2px solid #111':'1px solid #ddd',background:task===id?'#f3f4f6':'white'}}>{icon} {label}</button>)}</nav><main><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Décris ce que tu veux que l’IA fasse…" style={{width:'100%',minHeight:180,padding:14,borderRadius:12,border:'1px solid #ddd',resize:'vertical'}}/><button onClick={run} disabled={busy||!input.trim()} className="primary" style={{marginTop:10,width:'100%'}}>{busy?'⏳ L’IA travaille…':'✨ Lancer le Centre IA'}</button>{error&&<div style={{marginTop:12,padding:12,borderRadius:10,background:'#fee2e2',color:'#991b1b'}}>{error}</div>}{result&&<pre style={{whiteSpace:'pre-wrap',marginTop:14,padding:16,borderRadius:12,background:'#f7f7f7',maxHeight:420,overflow:'auto'}}>{result}</pre>}</main></div></div></div>;
}
