import React,{useState}from'react';import{supabase}from'../lib/supabase';
export default function MarketingAssistant({products=[]}){
 const[productId,setProductId]=useState(products[0]?.id||'');const[channels,setChannels]=useState(['WhatsApp','Facebook','Instagram','SMS']);const[result,setResult]=useState(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const product=products.find(p=>p.id===productId)||products[0];
 const toggle=c=>setChannels(x=>x.includes(c)?x.filter(v=>v!==c):[...x,c]);
 const generate=async()=>{if(!product)return;setBusy(true);setError('');try{const{data,error}=await supabase.functions.invoke('pjd-ai-marketing',{body:{product,channels}});if(error)throw new Error(error.message);if(data?.error)throw new Error(data.error);setResult(data.result)}catch(e){setError(e.message||'Impossible de générer la campagne.')}finally{setBusy(false)}};
 return <section style={{marginTop:20,padding:18,border:'1px solid #e5e7eb',borderRadius:18,background:'#fff'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><span style={{fontSize:12,fontWeight:900,color:'#f97316'}}>IA MARKETING PJD</span><h3 style={{margin:'4px 0'}}>🤖 Générateur de campagne</h3><p style={{margin:0,color:'#6b7280'}}>Une deuxième IA transforme un produit en contenus prêts à adapter par canal.</p></div></div>
 <select value={productId} onChange={e=>setProductId(e.target.value)} style={{marginTop:14,padding:11,width:'100%',maxWidth:480}}><option value="">Choisir un produit</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {Number(p.price||0).toLocaleString('fr-FR')} FCFA</option>)}</select>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'12px 0'}}>{['WhatsApp','Facebook','Instagram','SMS'].map(c=><button key={c} onClick={()=>toggle(c)} style={{padding:'8px 12px',borderRadius:999,border:channels.includes(c)?'2px solid #f97316':'1px solid #ddd',background:channels.includes(c)?'#fff7ed':'#fff'}}>{channels.includes(c)?'✓ ':''}{c}</button>)}</div>
 <button onClick={generate} disabled={busy||!product} style={{padding:'11px 16px',border:0,borderRadius:12,background:'#111827',color:'#fff',fontWeight:800}}>{busy?'Génération…':'✨ Générer la campagne'}</button>
 {error&&<div style={{marginTop:12,padding:12,borderRadius:10,background:'#fee2e2',color:'#991b1b'}}>{error}</div>}
 {result&&<div style={{marginTop:16,display:'grid',gap:12}}><div><b>{result.campaign_title}</b><p>{result.strategy}</p></div>{Object.entries(result.posts||{}).map(([c,text])=><article key={c} style={{padding:14,border:'1px solid #eee',borderRadius:12}}><strong>{c}</strong><p style={{whiteSpace:'pre-wrap'}}>{text}</p><button onClick={()=>navigator.clipboard?.writeText(text)}>Copier</button></article>)}{(result.hashtags||[]).length>0&&<small>Hashtags : {result.hashtags.join(' ')}</small>}</div>}
 <small style={{display:'block',marginTop:12,color:'#6b7280'}}>Aucune publication ni dépense publicitaire automatique. Le vendeur garde la validation finale.</small></section>;
}
