import React, { useEffect, useState } from 'react';
import { supabase } from './lib/supabase';
import { User, Store, Wallet, Package, Heart, Bell, Shield, Globe, Gift, HelpCircle, LogOut, ChevronRight, Pencil, Settings, ArrowLeft, Save, CreditCard, Landmark, Lock, Users, Eye, EyeOff } from 'lucide-react';
import './account.css';

const sections=[['personal','Informations personnelles','Nom, téléphone, e-mail, date de naissance et adresse',User],['shop','Ma boutique','Boutique, logo, catégories, contacts, horaires et paiement',Store],['wallet','Paiements & portefeuille','Solde, transactions, moyens de paiement et retrait',Wallet],['orders','Mes commandes','En cours, livrées, annulées, retours et factures',Package],['favorites','Mes favoris','Produits favoris et boutiques suivies',Heart],['notifications','Notifications','Commandes, promotions, messages et paiements',Bell],['security','Sécurité','Mot de passe, téléphone, 2FA et appareils',Shield],['preferences','Préférences','Langue, devise, pays, thème et notifications',Globe],['referral','Parrainage','Code, filleuls, commissions et récompenses',Gift],['help','Aide & assistance','Centre d’aide, support, FAQ et signalement',HelpCircle]];
const walletDefault={available:0,pending:0,withdrawal_method:'',withdrawal_account:'',withdrawal_name:'',withdrawal_country:'Cameroon'};
const detail={orders:['Commandes en cours','Commandes livrées','Commandes annulées','Retours / remboursements','Factures'],favorites:['Produits favoris','Boutiques suivies'],referral:['Mon code de parrainage','Inviter un ami','Nombre de filleuls','Commissions gagnées','Historique des récompenses'],help:['Centre d’aide','Contacter le support','Signaler un problème','FAQ','Conditions générales','Politique de confidentialité']};

export default function AccountPage({session,onBack}){
 const [current,setCurrent]=useState(session||null),[profile,setProfile]=useState({}),[active,setActive]=useState(null),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const [password,setPassword]=useState({new:'',confirm:''}),[showPassword,setShowPassword]=useState(false);
 useEffect(()=>{if(session)setCurrent(session);else supabase.auth.getSession().then(({data})=>setCurrent(data.session));},[session]);
 useEffect(()=>{if(current?.user)load();},[current]);
 async function load(){const {data}=await supabase.from('users').select('*').eq('id',current.user.id).maybeSingle();const m=current.user.user_metadata||{};setProfile({...m,...(data||{}),shop:{...(m.shop||{})},wallet:{...walletDefault,...(m.wallet||{})},preferences:{language:'Français',currency:'FCFA',theme:'clair',country:'Cameroon',...(m.preferences||{})},notifications:{orders:true,promotions:true,messages:true,payments:true,...(m.notifications||{})}});}
 const patch=(k,v)=>setProfile(p=>({...p,[k]:v})),nested=(k,v)=>setProfile(p=>({...p,[k]:{...(p[k]||{}),...v}}));
 async function save(e){e?.preventDefault();if(!current?.user)return;setSaving(true);const db=await supabase.from('users').update({name:profile.name||'',phone:profile.phone||'',city:profile.city||'',address:profile.address||''}).eq('id',current.user.id);const meta={...profile};['id','email','role','created_at','updated_at'].forEach(k=>delete meta[k]);const au=await supabase.auth.updateUser({data:meta});setSaving(false);setMessage(db.error?.message||au.error?.message||'Modifications enregistrées.');}
 async function changePassword(e){e.preventDefault();if(password.new.length<6)return setMessage('Le mot de passe doit contenir au moins 6 caractères.');if(password.new!==password.confirm)return setMessage('Les mots de passe ne correspondent pas.');setSaving(true);const {error}=await supabase.auth.updateUser({password:password.new});setSaving(false);setMessage(error?.message||'Mot de passe modifié.');if(!error)setPassword({new:'',confirm:''});}
 async function logout(){await supabase.auth.signOut();setCurrent(null);onBack?.();}
 const name=profile.name||current?.user?.user_metadata?.name||current?.user?.email?.split('@')[0]||'Mon compte',email=current?.user?.email||'',role=String(profile.role||current?.user?.user_metadata?.role||'Acheteur').toLowerCase(),seller=['vendeur','seller','admin'].includes(role),wallet=profile.wallet||walletDefault;
 const Panel=({icon,title,children})=><section className="account-panel"><div className="panel-title"><span>{icon}</span><h2>{title}</h2></div>{message&&<div className="account-message">{message}</div>}{children}</section>;
 const Field=({label,value,onChange,type='text',disabled=false,placeholder='',required=false,full=false})=><label className={full?'field-full':''}><span>{label}</span><input type={type} value={value??''} onChange={e=>onChange?.(e.target.value)} disabled={disabled} placeholder={placeholder} required={required}/></label>;
 const SaveButton=()=> <button className="save-btn" disabled={saving}><Save/> {saving?'Enregistrement...':'Enregistrer les modifications'}</button>;
 function render(){
  if(active==='personal')return <form onSubmit={save}><Panel icon={<User/>} title="Informations personnelles"><div className="form-grid"><Field label="Nom et prénom" value={profile.name||''} onChange={v=>patch('name',v)} required/><Field label="Photo de profil (URL)" value={profile.avatar_url||''} onChange={v=>patch('avatar_url',v)} placeholder="https://..."/><Field label="Numéro de téléphone" value={profile.phone||''} onChange={v=>patch('phone',v)} placeholder="+237..."/><Field label="Adresse e-mail" value={email} disabled/><Field label="Date de naissance" type="date" value={profile.birth_date||''} onChange={v=>patch('birth_date',v)}/><Field label="Ville" value={profile.city||''} onChange={v=>patch('city',v)}/><Field label="Adresse" value={profile.address||''} onChange={v=>patch('address',v)} full/></div><SaveButton/></Panel></form>;
  if(active==='shop')return <form onSubmit={save}><Panel icon={<Store/>} title="Ma boutique"><div className="form-grid"><Field label="Nom de la boutique" value={profile.shop?.name||''} onChange={v=>nested('shop',{name:v})} required/><Field label="Logo (URL)" value={profile.shop?.logo||''} onChange={v=>nested('shop',{logo:v})}/><Field label="Description" value={profile.shop?.description||''} onChange={v=>nested('shop',{description:v})} full/><Field label="Catégories" value={profile.shop?.categories||''} onChange={v=>nested('shop',{categories:v})}/><Field label="Adresse" value={profile.shop?.address||''} onChange={v=>nested('shop',{address:v})}/><Field label="Contacts" value={profile.shop?.contacts||''} onChange={v=>nested('shop',{contacts:v})}/><Field label="Horaires" value={profile.shop?.hours||''} onChange={v=>nested('shop',{hours:v})}/><Field label="Informations de paiement" value={profile.shop?.payment_info||''} onChange={v=>nested('shop',{payment_info:v})} full/></div><div className="sub-card"><Users/><div><b>Vendeurs / employés</b><p>Gestion des membres de l’équipe depuis le tableau de bord vendeur.</p></div></div><SaveButton/></Panel></form>;
  if(active==='wallet')return <form onSubmit={save}><Panel icon={<Wallet/>} title="Paiements & portefeuille"><div className="wallet-cards"><div><small>Solde disponible</small><strong>{Number(wallet.available||0).toLocaleString('fr-FR')} FCFA</strong></div><div><small>Revenus en attente</small><strong>{Number(wallet.pending||0).toLocaleString('fr-FR')} FCFA</strong></div></div><div className="form-grid"><Field label="Moyen de retrait" value={wallet.withdrawal_method} onChange={v=>nested('wallet',{withdrawal_method:v})} placeholder="MTN Mobile Money / Orange Money / Banque"/><Field label="Numéro / compte de retrait" value={wallet.withdrawal_account} onChange={v=>nested('wallet',{withdrawal_account:v})} placeholder="Numéro Mobile Money ou RIB"/><Field label="Nom du titulaire" value={wallet.withdrawal_name} onChange={v=>nested('wallet',{withdrawal_name:v})}/><Field label="Pays du compte" value={wallet.withdrawal_country} onChange={v=>nested('wallet',{withdrawal_country:v})}/></div><div className="wallet-actions"><button type="button" className="feature-action"><CreditCard/> Moyens de paiement</button><button type="button" className="feature-action"><Landmark/> Historique des transactions</button><button type="button" className="feature-action"><Wallet/> Demander un retrait</button><button type="button" className="feature-action">📈 Commissions</button></div><SaveButton/></Panel></form>;
  if(active==='security')return <Panel icon={<Shield/>} title="Sécurité"><form onSubmit={changePassword}><div className="form-grid"><Field label="Nouveau mot de passe" type={showPassword?'text':'password'} value={password.new} onChange={v=>setPassword(p=>({...p,new:v}))}/><Field label="Confirmer le mot de passe" type={showPassword?'text':'password'} value={password.confirm} onChange={v=>setPassword(p=>({...p,confirm:v}))}/></div><button type="button" className="secondary-action" onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff/>:<Eye/>} {showPassword?'Masquer':'Afficher'}</button><button className="save-btn" disabled={saving}><Lock/> Modifier le mot de passe</button></form><div className="feature-list"><button>Vérification du numéro<ChevronRight/></button><button>Authentification à deux facteurs (2FA)<ChevronRight/></button><button>Appareils connectés<ChevronRight/></button><button>Historique des connexions<ChevronRight/></button><button>Déconnexion de tous les appareils<ChevronRight/></button></div></Panel>;
  if(active==='preferences')return <form onSubmit={save}><Panel icon={<Globe/>} title="Préférences"><div className="form-grid"><Select label="Langue" value={profile.preferences?.language} options={['Français','English']} onChange={v=>nested('preferences',{language:v})}/><Select label="Devise" value={profile.preferences?.currency} options={['FCFA','EUR','USD','GBP']} onChange={v=>nested('preferences',{currency:v})}/><Select label="Mode" value={profile.preferences?.theme} options={['clair','sombre','système']} onChange={v=>nested('preferences',{theme:v})}/><Field label="Pays" value={profile.preferences?.country} onChange={v=>nested('preferences',{country:v})}/></div><SaveButton/></Panel></form>;
  if(active==='notifications')return <form onSubmit={save}><Panel icon={<Bell/>} title="Notifications"><Toggle label="Notifications de commandes" value={profile.notifications?.orders} onChange={v=>nested('notifications',{orders:v})}/><Toggle label="Promotions" value={profile.notifications?.promotions} onChange={v=>nested('notifications',{promotions:v})}/><Toggle label="Messages" value={profile.notifications?.messages} onChange={v=>nested('notifications',{messages:v})}/><Toggle label="Alertes de paiement" value={profile.notifications?.payments} onChange={v=>nested('notifications',{payments:v})}/><SaveButton/></Panel></form>;
  const items=detail[active]||[];return <Panel icon={React.createElement(sections.find(s=>s[0]===active)?.[3]||HelpCircle)} title={sections.find(s=>s[0]===active)?.[1]||''}><p>{sections.find(s=>s[0]===active)?.[2]}</p><div className="feature-list">{items.map(x=><button key={x}>{x}<ChevronRight/></button>)}</div></Panel>;
 }
 if(!current)return <main className="account-page"><div className="account-panel"><h2>Connexion requise</h2><p>Connectez-vous pour accéder à votre compte.</p></div></main>;
 return <main className="account-page"><div className="account-wrap"><button className="account-back" onClick={onBack}><ArrowLeft/> MON COMPTE</button><section className="account-hero"><div className="avatar">{profile.avatar_url?<img src={profile.avatar_url} alt="Profil"/>:name.charAt(0).toUpperCase()}</div><div className="account-identity"><h1>{name}</h1><p>{profile.phone||'Téléphone non renseigné'} · {email}</p><span className="role-badge">{seller?'Client • Vendeur':'Client'}</span></div><button className="edit-profile" onClick={()=>setActive('personal')}><Pencil size={17}/> Modifier le profil</button></section><div className="account-layout"><aside className="account-menu">{sections.filter(s=>s[0]!=='shop'||seller).map(([id,title,desc,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}><span><Icon/><b>{title}</b></span><small>{desc}</small><ChevronRight/></button>)}<button className="logout-btn" onClick={logout}><LogOut/><b>Se déconnecter</b></button></aside><section className="account-content">{!active?<><div className="account-welcome"><Settings/><div><h2>Bienvenue dans votre compte</h2><p>Renseignez et gérez toutes les informations de votre compte, de votre boutique et de votre portefeuille.</p></div></div><div className="account-grid">{sections.filter(s=>s[0]!=='shop'||seller).map(([id,title,desc,Icon])=><button key={id} onClick={()=>setActive(id)}><Icon/><div><b>{title}</b><small>{desc}</small></div><ChevronRight/></button>)}</div></>:render()}</section></div></div></main>;
}
function Select({label,value,options,onChange}){return <label><span>{label}</span><select value={value||options[0]} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Toggle({label,value,onChange}){return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/></label>}
