import React,{useEffect,useMemo,useState}from'react';
import{ArrowDownToLine,RefreshCw,CheckCircle2,XCircle,Clock,Wallet,Loader2}from'lucide-react';
import{supabase}from'./lib/supabase';
const money=v=>`${Number(v||0).toLocaleString('fr-FR')} FCFA`;
const fmt=v=>v?new Date(v).toLocaleString('fr-FR'):'';
const S={grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:14},card:{background:'#fff',border:'1px solid #e5e7eb',borderRadius:16,padding:18},btn:{border:0,borderRadius:9,padding:'10px 13px',fontWeight:800,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:7},input:{padding:11,border:'1px solid #d1d5db',borderRadius:9,width:'100%',boxSizing:'border-box'},row:{padding:'14px 0',borderBottom:'1px solid #eee',display:'flex',justifyContent:'space-between',gap:14,alignItems:'center',flexWrap:'wrap'}};
export default function AdminWithdrawals(){
 const[rows,setRows]=useState([]),[available,setAvailable]=useState(0),[amount,setAmount]=useState(''),[method,setMethod]=useState('MTN'),[phone,setPhone]=useState(''),[accountName,setAccountName]=useState(''),[note,setNote]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);const[{data,error},{data:orders}]=await Promise.all([supabase.from('admin_withdrawals').select('*').order('requested_at',{ascending:false}).limit(100),supabase.from('orders').select('platform_fee,status,payment_status').limit(5000)]);if(error)setMessage(error.message);setRows(data||[]);const fees=(orders||[]).filter(o=>['paid','success','successful','completed','complete'].includes(String(o.payment_status||o.status||'').toLowerCase())).reduce((s,o)=>s+Number(o.platform_fee||0),0);const reserved=(data||[]).filter(x=>['pending','approved','paid'].includes(String(x.status||'').toLowerCase())).reduce((s,x)=>s+Number(x.amount||0),0);setAvailable(Math.max(0,fees-reserved));setLoading(false)};
 useEffect(()=>{load()},[]);
 const pending=useMemo(()=>rows.filter(x=>x.status==='pending'),[rows]);
 const request=async()=>{const n=Number(amount);if(!Number.isFinite(n)||n<100){setMessage('Le montant minimum est de 100 FCFA.');return}if(n>available){setMessage('Solde administrateur insuffisant.');return}setBusy(true);const{error}=await supabase.rpc('admin_request_withdrawal',{p_amount:n,p_method:method,p_phone:phone,p_account_name:accountName});setBusy(false);if(error){setMessage(error.message);return}setAmount('');setPhone('');setAccountName('');setMessage('Demande de retrait administrateur créée.');load()};
 const decide=async(id,status)=>{const text=status==='rejected'?'Refus du retrait ?':'Valider cette demande ?';if(!window.confirm(text))return;setBusy(true);const{error}=await supabase.rpc('admin_mark_withdrawal',{p_id:id,p_status:status,p_note:note||null});setBusy(false);setMessage(error?error.message:`Retrait ${status==='rejected'?'refusé':'approuvé'}.`);if(!error){setNote('');load()}};
 if(loading)return <div style={{padding:30,textAlign:'center'}}><Loader2/> Chargement des retraits...</div>;
 return <section>
  <div style={S.grid}>
   <div style={S.card}><Wallet size={22}/><small style={{display:'block',color:'#6b7280',marginTop:8}}>Solde disponible</small><strong style={{fontSize:25}}>{money(available)}</strong></div>
   <div style={S.card}><Clock size={22}/><small style={{display:'block',color:'#6b7280',marginTop:8}}>Demandes en attente</small><strong style={{fontSize:25}}>{pending.length}</strong></div>
   <div style={S.card}><ArrowDownToLine size={22}/><small style={{display:'block',color:'#6b7280',marginTop:8}}>Retraits traités</small><strong style={{fontSize:25}}>{rows.filter(x=>['paid','approved'].includes(x.status)).length}</strong></div>
  </div>
  <div style={{...S.card,marginTop:18}}><h2 style={{marginTop:0}}>Retrait des revenus administrateur</h2><p style={{color:'#6b7280'}}>Le solde disponible est calculé à partir des commissions plateforme des commandes payées, moins les retraits administrateur réservés.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><input style={S.input} type="number" min="100" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Montant FCFA"/><select style={S.input} value={method} onChange={e=>setMethod(e.target.value)}><option value="MTN">MTN Mobile Money</option><option value="ORANGEMONEY">Orange Money</option><option value="WAVE">Wave</option><option value="BANK">Compte bancaire</option></select><input style={S.input} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Numéro / compte"/><input style={S.input} value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="Nom du titulaire"/></div><button disabled={busy} style={{...S.btn,background:'#f97316',color:'#fff',marginTop:12}} onClick={request}><ArrowDownToLine size={16}/> Demander un retrait</button></div>
  <div style={{...S.card,marginTop:18}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><h2>Historique des retraits</h2><button style={{...S.btn,background:'#f3f4f6'}} onClick={load}><RefreshCw size={16}/> Actualiser</button></div>{rows.length===0?<p>Aucun retrait administrateur.</p>:rows.map(r=><div key={r.id} style={S.row}><div><b>{money(r.amount)}</b><small style={{display:'block',color:'#6b7280'}}>{r.method} · {r.phone||'—'} · {r.account_name||'—'} · {fmt(r.requested_at)}</small><small style={{display:'block'}}>Statut : <b>{r.status}</b>{r.payment_reference?` · Réf. ${r.payment_reference}`:''}</small></div>{r.status==='pending'&&<div style={{display:'flex',gap:7}}><button disabled={busy} style={{...S.btn,background:'#ecfdf5',color:'#166534'}} onClick={()=>decide(r.id,'approved')}><CheckCircle2 size={15}/> Approuver</button><button disabled={busy} style={{...S.btn,background:'#fef2f2',color:'#991b1b'}} onClick={()=>decide(r.id,'rejected')}><XCircle size={15}/> Refuser</button></div>}</div>)}</div>
  {message&&<div style={{...S.card,marginTop:14,background:'#fff7ed'}}>{message}</div>}
 </section>;
}
