import React,{useEffect,useMemo,useState}from'react';
import{ShieldCheck,Users,Store,Package,ShoppingBag,Wallet,BarChart3,Settings,Search,Ban,CheckCircle2,RefreshCw,ArrowLeft,Loader2,Star,Megaphone,UserCog,Receipt,Link2,Trash2,Eye}from'lucide-react';
import{supabase}from'./lib/supabase';
const money=v=>`${Number(v||0).toLocaleString('fr-FR')} FCFA`;
const fmt=v=>v?new Date(v).toLocaleString('fr-FR'):'';
const S={page:{minHeight:'100vh',background:'#f7f8fa',color:'#111827',fontFamily:'Inter,system-ui,sans-serif'},header:{background:'#111827',color:'#fff',padding:'18px 5%',display:'flex',alignItems:'center',justifyContent:'space-between',gap:20},wrap:{maxWidth:1500,margin:'auto',padding:'24px 4%'},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:14},card:{background:'#fff',border:'1px solid #e5e7eb',borderRadius:16,padding:18},btn:{border:0,borderRadius:9,padding:'9px 12px',fontWeight:800,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:6},input:{padding:11,border:'1px solid #d1d5db',borderRadius:9,width:'100%',boxSizing:'border-box'},row:{padding:'13px 0',borderBottom:'1px solid #eee',display:'flex',justifyContent:'space-between',gap:14,alignItems:'center',flexWrap:'wrap'}};
const nav=[['overview','Vue générale',BarChart3],['users','Utilisateurs',Users],['shops','Boutiques',Store],['products','Produits',Package],['orders','Commandes',ShoppingBag],['finance','Finances',Wallet],['reviews','Avis',Star],['ads','Publicité',Megaphone],['affiliates','Affiliation',Link2],['subscriptions','Abonnements',Receipt],['audit','Journal',Eye],['settings','Sécurité',Settings]];
export default function AdminDashboard({onBack}){
 const[session,setSession]=useState(null),[role,setRole]=useState(''),[users,setUsers]=useState([]),[shops,setShops]=useState([]),[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[payments,setPayments]=useState([]),[withdrawals,setWithdrawals]=useState([]),[reviews,setReviews]=useState([]),[ads,setAds]=useState([]),[affiliates,setAffiliates]=useState([]),[subscriptions,setSubscriptions]=useState([]),[logs,setLogs]=useState([]),[tab,setTab]=useState('overview'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session){const{data:u}=await supabase.from('users').select('role').eq('id',data.session.user.id).maybeSingle();setRole(u?.role||'');load()}else setLoading(false)})},[]);
 async function load(){setLoading(true);const results=await Promise.all([
  supabase.from('users').select('id,name,email,role,suspended,shop_id,created_at').order('created_at',{ascending:false}).limit(1000),
  supabase.from('shops').select('id,owner_id,shop_name,category,status,commission_rate,rating,followers_count,plan_code,created_at').order('created_at',{ascending:false}).limit(1000),
  supabase.from('digital_products').select('id,title,price,promo_price,status,category,seller_id,shop_id,sales,downloads,stock,created_at').order('created_at',{ascending:false}).limit(1000),
  supabase.from('orders').select('id,user_id,total,status,payment_method,platform_fee,seller_total,discount_amount,created_at').order('created_at',{ascending:false}).limit(1000),
  supabase.from('payments').select('id,user_id,order_id,amount,method,status,tx_id,payment_ref,operator,created_at,updated_at').order('created_at',{ascending:false}).limit(1000),
  supabase.from('withdrawal_requests').select('*').order('requested_at',{ascending:false}).limit(1000),
  supabase.from('reviews').select('*').order('created_at',{ascending:false}).limit(1000),
  supabase.from('pjd_ads').select('*').order('created_at',{ascending:false}).limit(1000),
  supabase.from('affiliates').select('*').order('created_at',{ascending:false}).limit(1000),
  supabase.from('subscriptions').select('*').order('created_at',{ascending:false}).limit(1000),
  supabase.from('audit_log').select('*').order('created_at',{ascending:false}).limit(1000)
 ]);setUsers(results[0].data||[]);setShops(results[1].data||[]);setProducts(results[2].data||[]);setOrders(results[3].data||[]);setPayments(results[4].data||[]);setWithdrawals(results[5].data||[]);setReviews(results[6].data||[]);setAds(results[7].data||[]);setAffiliates(results[8].data||[]);setSubscriptions(results[9].data||[]);setLogs(results[10].data||[]);setLoading(false)}
 async function change(table,id,patch,label){setBusy(true);const{error}=await supabase.from(table).update(patch).eq('id',id);setBusy(false);setMessage(error?error.message:label);if(!error)load()}
 async function remove(table,id,label){if(!window.confirm('Confirmer cette suppression ?'))return;setBusy(true);const{error}=await supabase.from(table).delete().eq('id',id);setBusy(false);setMessage(error?error.message:label);if(!error)load()}
 const filteredUsers=useMemo(()=>users.filter(x=>!search||`${x.name||''} ${x.email||''} ${x.role||''}`.toLowerCase().includes(search.toLowerCase())),[users,search]);
 const revenue=orders.reduce((s,o)=>s+Number(o.total||0),0),fees=orders.reduce((s,o)=>s+Number(o.platform_fee||0),0),paid=payments.filter(p=>['paid','success','successful','completed','complete'].includes(String(p.status||'').toLowerCase())).reduce((s,p)=>s+Number(p.amount||0),0);
 if(loading)return <div style={S.page}><div style={{padding:60,textAlign:'center'}}><Loader2 className="spin"/> Chargement du centre d’administration...</div></div>;
 if(!session)return <div style={S.page}><main style={S.wrap}><button style={S.btn} onClick={onBack}><ArrowLeft/> Retour</button><h1>Administration</h1><p>Connectez-vous avec un compte administrateur.</p></main></div>;
 if(role!=='admin')return <div style={S.page}><main style={S.wrap}><button style={S.btn} onClick={onBack}><ArrowLeft/> Retour</button><div style={{...S.card,marginTop:30}}><ShieldCheck size={40}/><h1>Accès administrateur refusé</h1><p>Votre compte ne possède pas le rôle administrateur.</p></div></main></div>;
 const Action=({children,onClick,danger=false})=><button disabled={busy} style={{...S.btn,background:danger?'#fef2f2':'#ecfdf5',color:danger?'#991b1b':'#166534'}} onClick={onClick}>{children}</button>;
 return <div style={S.page}><header style={S.header}><div><small style={{color:'#fb923c',fontWeight:900}}>PJD MARKET</small><h1 style={{margin:'3px 0',fontSize:25}}>Centre de contrôle administrateur</h1><small>Contrôle des utilisateurs, boutiques, catalogue, ventes et finances</small></div><button style={{...S.btn,background:'#fff'}} onClick={onBack}><ArrowLeft size={17}/> Marketplace</button></header><main style={S.wrap}>{message&&<div style={{...S.card,marginBottom:15,background:'#ecfdf5'}}>{message}</div>}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:22}}>{nav.map(([id,label,Icon])=><button key={id} style={{...S.btn,background:tab===id?'#f97316':'#fff',color:tab===id?'#fff':'#111827',border:'1px solid #e5e7eb'}} onClick={()=>{setTab(id);setSearch('')}}><Icon size={16}/>{label}</button>)}<button style={{...S.btn,background:'#fff',border:'1px solid #e5e7eb',marginLeft:'auto'}} onClick={load}><RefreshCw size={16}/> Actualiser</button></div>
 {tab==='overview'&&<><div style={S.grid}>{[[Users,'Utilisateurs',users.length],[Store,'Boutiques',shops.length],[Package,'Produits',products.length],[ShoppingBag,'Commandes',orders.length],[Wallet,'CA commandes',money(revenue)],[Receipt,'Paiements confirmés',money(paid)],[BarChart3,'Commissions plateforme',money(fees)],[Ban,'Comptes suspendus',users.filter(x=>x.suspended).length]].map(([I,a,b])=><div style={S.card} key={a}><I size={22}/><small style={{display:'block',color:'#6b7280',marginTop:9}}>{a}</small><strong style={{fontSize:22}}>{b}</strong></div>)}</div><div style={{...S.card,marginTop:18}}><h2>Tableau de bord global</h2><p>Depuis cet espace, l’administrateur peut surveiller et modérer les comptes, boutiques, produits, commandes, paiements, retraits, avis, publicité, affiliation et abonnements.</p><div style={S.grid}><div><b>Produits actifs</b><div>{products.filter(p=>['active','actif','published'].includes(String(p.status||'').toLowerCase())).length}</div></div><div><b>Boutiques certifiées</b><div>{shops.filter(s=>s.status==='verified').length}</div></div><div><b>Retraits en attente</b><div>{withdrawals.filter(w=>['pending','requested','en_attente'].includes(String(w.status||'').toLowerCase())).length}</div></div><div><b>Avis reçus</b><div>{reviews.length}</div></div></div></div></>}
 {tab==='users'&&<section style={S.card}><h2>Gestion des utilisateurs</h2><div style={{display:'flex',gap:10,marginBottom:12}}><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher nom, e-mail ou rôle" style={S.input}/></div>{filteredUsers.map(u=><div key={u.id} style={S.row}><div><b>{u.name||'Utilisateur'}</b><span style={{marginLeft:10}}>{u.email}</span><small style={{display:'block',color:'#6b7280'}}>Rôle : {u.role||'client'} · {u.suspended?'SUSPENDU':'actif'} · {fmt(u.created_at)}</small></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><Action onClick={()=>change('users',u.id,{role:'admin'},'Utilisateur promu administrateur.')}><UserCog size={15}/> Admin</Action><Action onClick={()=>change('users',u.id,{role:'vendeur'},'Utilisateur défini comme vendeur.')}><Store size={15}/> Vendeur</Action><Action onClick={()=>change('users',u.id,{role:'client'},'Utilisateur défini comme client.')}>Client</Action><Action danger onClick={()=>change('users',u.id,{suspended:!u.suspended},u.suspended?'Compte réactivé.':'Compte suspendu.')}><Ban size={15}/>{u.suspended?'Réactiver':'Suspendre'}</Action></div></div>)}</section>}
 {tab==='shops'&&<section style={S.card}><h2>Boutiques & vendeurs</h2>{shops.map(s=><div key={s.id} style={S.row}><div><b>{s.shop_name}</b><small style={{display:'block',color:'#6b7280'}}>{s.category||'Marketplace'} · statut: {s.status} · plan: {s.plan_code||'—'} · commission: {s.commission_rate||0}% · note: {s.rating||0} · abonnés: {s.followers_count||0}</small></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><Action onClick={()=>change('shops',s.id,{status:'verified'},'Boutique certifiée.') }><ShieldCheck size={15}/> Certifier</Action><Action onClick={()=>change('shops',s.id,{status:'active'},'Boutique activée.') }><CheckCircle2 size={15}/> Activer</Action><Action danger onClick={()=>change('shops',s.id,{status:'suspended'},'Boutique suspendue.')}><Ban size={15}/> Suspendre</Action></div></div>)}</section>}
 {tab==='products'&&<section style={S.card}><h2>Modération du catalogue</h2>{products.map(p=><div key={p.id} style={S.row}><div><b>{p.title}</b><small style={{display:'block',color:'#6b7280'}}>{p.category||'—'} · {money(p.price)} · promo {money(p.promo_price)} · stock {p.stock??0} · ventes {p.sales??0} · statut {p.status}</small></div><div style={{display:'flex',gap:7}}><Action onClick={()=>change('digital_products',p.id,{status:'active'},'Produit activé.')}><CheckCircle2 size={15}/> Activer</Action><Action danger onClick={()=>change('digital_products',p.id,{status:'suspended'},'Produit suspendu.')}><Ban size={15}/> Suspendre</Action></div></div>)}</section>}
 {tab==='orders'&&<section style={S.card}><h2>Commandes & paiements</h2>{orders.map(o=><div key={o.id} style={S.row}><div><b>Commande #{String(o.id).slice(0,8)}</b><span style={{marginLeft:10}}>{money(o.total)}</span><small style={{display:'block',color:'#6b7280'}}>{o.status} · {o.payment_method||'—'} · commission {money(o.platform_fee)} · vendeur {money(o.seller_total)} · {fmt(o.created_at)}</small></div><Action onClick={()=>change('orders',o.id,{status:'completed'},'Commande marquée terminée.')}>Terminer</Action></div>)}<h3 style={{marginTop:25}}>Derniers paiements</h3>{payments.slice(0,100).map(p=><div key={p.id} style={S.row}><div><b>{money(p.amount)}</b> · {p.method||p.operator||'—'}<small style={{display:'block',color:'#6b7280'}}>{p.status} · {p.tx_id||p.payment_ref||'sans référence'} · {fmt(p.created_at)}</small></div></div>)}</section>}
 {tab==='finance'&&<><div style={S.grid}><div style={S.card}><Wallet/><h2>{money(revenue)}</h2><p>Volume total des commandes</p></div><div style={S.card}><Wallet/><h2>{money(fees)}</h2><p>Commissions plateforme enregistrées</p></div><div style={S.card}><Wallet/><h2>{money(paid)}</h2><p>Paiements confirmés</p></div></div><section style={{...S.card,marginTop:18}}><h2>Demandes de retrait</h2>{withdrawals.map(w=><div key={w.id} style={S.row}><div><b>{money(w.amount)}</b><small style={{display:'block',color:'#6b7280'}}>{w.method||'—'} · {w.phone||w.account||'—'} · {w.status} · {fmt(w.requested_at)}</small></div><div style={{display:'flex',gap:7}}><Action onClick={()=>change('withdrawal_requests',w.id,{status:'approved',decided_at:new Date().toISOString()},'Retrait approuvé.')}>Approuver</Action><Action danger onClick={()=>change('withdrawal_requests',w.id,{status:'rejected',decided_at:new Date().toISOString()},'Retrait refusé.')}>Refuser</Action></div></div>)}</section></>}
 {tab==='reviews'&&<section style={S.card}><h2>Modération des avis</h2>{reviews.map(r=><div key={r.id} style={S.row}><div><b>{'★'.repeat(Math.max(0,Math.min(5,Number(r.rating||0))))}</b><p style={{margin:'5px 0'}}>{r.comment||'Sans commentaire'}</p><small>{fmt(r.created_at)}</small></div><Action danger onClick={()=>remove('reviews',r.id,'Avis supprimé.') }><Trash2 size={15}/> Supprimer</Action></div>)}</section>}
 {tab==='ads'&&<section style={S.card}><h2>Publicité PJD</h2>{ads.map(a=><div key={a.id} style={S.row}><div><b>{a.placement||'Publicité'}</b><small style={{display:'block',color:'#6b7280'}}>Budget {money(a.budget)} · {a.duration_days||0} jours · impressions {a.impressions||0} · clics {a.clicks||0} · {a.status}</small></div><div><Action onClick={()=>change('pjd_ads',a.id,{status:'active'},'Campagne activée.')}>Activer</Action><Action danger onClick={()=>change('pjd_ads',a.id,{status:'suspended'},'Campagne suspendue.')}>Suspendre</Action></div></div>)}</section>}
 {tab==='affiliates'&&<section style={S.card}><h2>Programme d’affiliation</h2>{affiliates.map(a=><div key={a.id} style={S.row}><div><b>{a.affiliate_code}</b><small style={{display:'block',color:'#6b7280'}}>Statut {a.status} · taux {a.commission_rate||0}% · ventes {money(a.total_sales)} · commission {money(a.total_commission)} · disponible {money(a.available_commission)}</small></div><div><Action onClick={()=>change('affiliates',a.id,{status:'active'},'Affilié activé.')}>Activer</Action><Action danger onClick={()=>change('affiliates',a.id,{status:'suspended'},'Affilié suspendu.')}>Suspendre</Action></div></div>)}</section>}
 {tab==='subscriptions'&&<section style={S.card}><h2>Abonnements</h2>{subscriptions.map(s=><div key={s.id} style={S.row}><div><b>{s.plan||'Plan'}</b><small style={{display:'block',color:'#6b7280'}}>{money(s.amount)} · {s.status} · {fmt(s.starts_at)} → {fmt(s.ends_at)}</small></div><Action onClick={()=>change('subscriptions',s.id,{status:'active'},'Abonnement activé.')}>Activer</Action></div>)}</section>}
 {tab==='audit'&&<section style={S.card}><h2>Journal d’activité</h2>{logs.map(l=><div key={l.id} style={S.row}><div><b>{l.action||'action'}</b><small style={{display:'block',color:'#6b7280'}}>{l.actor||'—'} · {l.resource||'—'} · {l.result||'—'} · {fmt(l.created_at)}</small></div></div>)}</section>}
 {tab==='settings'&&<section style={S.card}><ShieldCheck/><h2>Sécurité & gouvernance</h2><ul><li>Rôle administrateur contrôlé côté base de données.</li><li>Gestion des rôles client, vendeur et administrateur.</li><li>Suspension/réactivation des comptes.</li><li>Certification et suspension des boutiques.</li><li>Modération des produits et avis.</li><li>Surveillance des paiements et retraits.</li><li>Suivi publicité, affiliation et abonnements.</li><li>Journal d’activité pour les opérations sensibles.</li></ul><p><b>Important :</b> les clés secrètes et mots de passe ne doivent jamais être stockés dans le frontend.</p></section>}
 </main></div>;
}