import React,{useEffect,useState}from'react';
import AdminDashboard from'./AdminDashboard.jsx';
import AdminSellerChat from'./AdminSellerChat.jsx';
import ShopVerificationAdmin from'./ShopVerificationAdmin.jsx';
import PromoCodesPage from'./PromoCodesPage.jsx';
import{supabase}from'./lib/supabase';

export default function AdminDashboardV2(props){
 const[admin,setAdmin]=useState(false),[chat,setChat]=useState(false),[verify,setVerify]=useState(false),[promo,setPromo]=useState(false),[session,setSession]=useState(null);
 useEffect(()=>{let mounted=true;const check=async()=>{const{data}=await supabase.auth.getSession();if(!mounted)return;setSession(data.session);if(!data.session)return;const{data:aid}=await supabase.rpc('get_pjd_admin_id');setAdmin(aid===data.session.user.id)};check();const{data:{subscription}}=supabase.auth.onAuthStateChange(()=>check());return()=>{mounted=false;subscription.unsubscribe()}},[]);
 return <div className="pjd-admin-shell"><AdminDashboard {...props}/>{admin&&<div className="pjd-admin-tools" aria-label="Actions administrateur"><button className="verify" onClick={()=>setVerify(true)}>✓ Vérification des boutiques</button><button className="promo" onClick={()=>setPromo(true)}>🏷️ Codes promo</button><button className="chat" onClick={()=>setChat(true)}>💬 Messages vendeurs</button></div>}{verify&&<div className="pjd-overlay"><ShopVerificationAdmin onBack={()=>setVerify(false)}/></div>}{promo&&<div className="pjd-overlay"><PromoCodesPage session={session} onBack={()=>setPromo(false)}/></div>}{chat&&<div className="pjd-overlay"><AdminSellerChat session={session} mode="admin" onBack={()=>setChat(false)}/></div>}<style>{`.pjd-admin-shell{min-height:100vh;background:#f5f7fa}.pjd-admin-tools{position:fixed;left:12px;bottom:12px;z-index:10001;display:flex;gap:8px;width:calc(100% - 24px);max-width:760px;padding:8px;background:#fff;border:1px solid #e5e7eb;border-radius:14px;box-shadow:0 10px 30px rgba(15,23,42,.16)}.pjd-admin-tools button{flex:1;min-height:44px;border:0;border-radius:10px;padding:8px 10px;font-weight:800;cursor:pointer}.pjd-admin-tools .verify{background:#111827;color:#fff}.pjd-admin-tools .promo{background:#f97316;color:#fff}.pjd-admin-tools .chat{background:#fff;color:#111827;border:1px solid #dbe1e8}.pjd-overlay{position:fixed;inset:0;z-index:10000;background:#fff;overflow:auto}@media(max-width:560px){.pjd-admin-tools{gap:5px;padding:6px}.pjd-admin-tools button{font-size:10px;padding:7px 4px;min-height:48px}}`}</style></div>
}