import React,{useEffect,useMemo,useState}from'react';
import{supabase}from'./lib/supabase';
import{ArrowLeft,Copy,Gift,MousePointerClick,ShoppingBag,Wallet,Trophy,Share2,CheckCircle,Users,Banknote,Loader2}from'lucide-react';
const money=v=>Number(v||0).toLocaleString('fr-FR')+' FCFA';
const periods=[['monthly','Ce mois'],['weekly','Cette semaine'],['daily',"Aujourd'hui"],['all_time','Tous les temps']];
function periodRange(p){const now=new Date(),end=new Date(now);let start=new Date(now);if(p==='daily')start=new Date(now.getFullYear(),now.getMonth(),now.getDate());if(p==='weekly'){const d=(now.getDay()+6)%7;start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-d)}if(p==='monthly')start=new Date(now.getFullYear(),now.getMonth(),1);if(p==='all_time')start=new Date('2020-01-01T00:00:00');return[start.toISOString().slice(0,10),end.toISOString().slice(0,10)]}
const card={background:'#fff',borderRadius:18,padding:20,boxShadow:'0 8px 30px rgba(17,24,39,.06)'};
export default function AffiliatePage({session,onBack}){
 const[affiliate,setAffiliate]=useState(null),[referralCode,setReferralCode]=useState(''),[ranking,setRanking]=useState([]),[period,setPeriod]=useState('monthly'),[loading,setLoading]=useState(true),[copied,setCopied]=useState(''),[message,setMessage]=useState(''),[amount,setAmount]=useState(''),[method,setMethod]=useState('mtn_momo'),[phone,setPhone]=useState(''),[payoutLoading,setPayoutLoading]=useState(false),[payouts,setPayouts]=useState([]);
 const load=async(p=period)=>{if(!session?.user?.id)return;setLoading(true);const[a,rc]=await Promise.all([supabase.rpc('activate_my_affiliate'),supabase.rpc('get_or_create_referral_code')]);if(a.error){setMessage(a.error.message);setLoading(false);return}setAffiliate(a.data);if(!rc.error)setReferralCode(rc.data||'');const[start,end]=periodRange(p);const rr=await supabase.rpc('refresh_affiliate_rankings',{p_period:p,p_start:start,p_end:end});if(rr.error)setMessage(rr.error.message);const{data:r,error:re}=await supabase.from('affiliate_leaderboard').select('*').eq('period',p).eq('period_start',start).eq('period_end',end).order('rank',{ascending:true}).limit(100);if(re)setMessage(re.message);setRanking(r||[]);const{data:ps}=await supabase.from('affiliate_payouts').select('id,amount,method,phone_number,status,requested_at,processed_at,transaction_id').eq('affiliate_id',a.data.id).order('requested_at',{ascending:false}).limit(20);setPayouts(ps||[]);setLoading(false)};
 useEffect(()=>{load()},[session?.user?.id,period]);
 const affiliateLink=useMemo(()=>affiliate?`${window.location.origin}/?aff=${affiliate.affiliate_code}`:'',[affiliate]);
 const referralLink=useMemo(()=>referralCode?`${window.location.origin}/?ref=${referralCode}`:'',[referralCode]);
 useEffect(()=>{const q=new URLSearchParams(window.location.search),aff=q.get('aff'),ref=q.get('ref');if(aff){const code=aff.toUpperCase();localStorage.setItem('pjd-affiliate-code',code);supabase.rpc('track_affiliate_click',{p_code:code,p_product_id:null}).then(({data})=>{if(data)localStorage.setItem('pjd-affiliate-click',data)})}if(ref)localStorage.setItem('pjd-referral-code',ref.toUpperCase())},[]);
 const copy=async(type,link)=>{try{await navigator.clipboard.writeText(link);setCopied(type);setTimeout(()=>setCopied(''),1800)}catch{setMessage('Impossible de copier le lien.')}};
 const share=async(type,link)=>{if(navigator.share)await navigator.share({title:'PJD Market',text:type==='affiliate'?'Découvrez ce produit avec mon lien PJD Market':'Rejoignez PJD Market avec mon invitation',url:link});else copy(type,link)};
 const requestPayout=async()=>{const value=Number(amount);if(value<5000){setMessage('Le retrait minimum est de 5 000 FCFA.');return}if(!/^6\d{8}$/.test(phone.replace(/\D/g,''))&&!/^2376\d{8}$/.test(phone.replace(/\D/g,''))){setMessage('Numéro camerounais invalide. Utilisez 6XXXXXXXX ou 2376XXXXXXXX.');return}setPayoutLoading(true);setMessage('');const{data,error}=await supabase.rpc('request_affiliate_payout',{p_amount:value,p_method:method,p_phone_number:phone.replace(/\D/g,'')});if(error){setMessage(error.message)}else{setMessage('Demande de retrait enregistrée.');setAmount('');await load(period)}setPayoutLoading(false)};
 const me=ranking.find(x=>x.affiliate_id===affiliate?.id);
 if(!session?.user)return <div style={{padding:30}}>Connectez-vous pour accéder à l’affiliation.</div>;
 return <div style={{minHeight:'100vh',background:'#f6f7fb',padding:'24px 16px 60px'}}><div style={{maxWidth:1100,margin:'0 auto'}}><button onClick={onBack} style={{display:'inline-flex',alignItems:'center',gap:8,border:0,background:'transparent',cursor:'pointer',marginBottom:18}}><ArrowLeft size={18}/> Retour</button>
 <header style={{background:'linear-gradient(135deg,#111827,#27272a)',color:'#fff',borderRadius:22,padding:28,marginBottom:20}}><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'center',flexWrap:'wrap'}}><div><div style={{display:'flex',alignItems:'center',gap:10,color:'#fbbf24'}}><Gift size={22}/><b>AFFILIATION & PARRAINAGE PJD MARKET</b></div><h1 style={{margin:'8px 0',fontSize:30}}>Gagnez en recommandant PJD Market</h1><p style={{margin:0,opacity:.8}}>Affiliation = commissions sur les ventes. Parrainage = récompenses liées aux utilisateurs invités et à leurs actions éligibles.</p></div><Trophy size={58}/></div></header>
 {message&&<div style={{background:'#fff7ed',border:'1px solid #fed7aa',padding:13,borderRadius:12,marginBottom:16}}>{message}</div>}
 {affiliate&&<>
 <section style={{...card,marginBottom:18}}><h2 style={{marginTop:0}}>🔗 Votre lien d’affiliation</h2><p style={{color:'#666'}}>Utilisez <b>?aff=</b> pour distinguer l’affiliation du parrainage.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><input readOnly value={affiliateLink} style={{flex:1,minWidth:240,padding:12,border:'1px solid #ddd',borderRadius:10}}/><button onClick={()=>copy('affiliate',affiliateLink)}>{copied==='affiliate'?<CheckCircle size={17}/>:<Copy size={17}/>} {copied==='affiliate'?'Copié':'Copier'}</button><button onClick={()=>share('affiliate',affiliateLink)}><Share2 size={17}/> Partager</button></div><b style={{display:'block',marginTop:10}}>Code affilié : {affiliate.affiliate_code} · Commission : {affiliate.commission_rate}%</b></section>
 <section style={{...card,marginBottom:18}}><h2 style={{marginTop:0}}>👥 Votre parrainage</h2><p style={{color:'#666'}}>Invitez des utilisateurs avec votre code personnel. Aucun paiement n’est déclenché pour un simple faux compte ou une simple visite.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><input readOnly value={referralLink} style={{flex:1,minWidth:240,padding:12,border:'1px solid #ddd',borderRadius:10}}/><button onClick={()=>copy('referral',referralLink)}>{copied==='referral'?<CheckCircle size={17}/>:<Copy size={17}/>} {copied==='referral'?'Copié':'Copier'}</button><button onClick={()=>share('referral',referralLink)}><Share2 size={17}/> Partager</button></div><b style={{display:'block',marginTop:10}}>Code parrainage : {referralCode}</b></section>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:14,marginBottom:20}}>{[[MousePointerClick,'Clics',affiliate.total_clicks],[ShoppingBag,'Commandes',affiliate.total_orders],[Wallet,'Commissions',money(affiliate.total_commission)],[Wallet,'Disponible',money(affiliate.available_commission)]].map(([I,l,v])=><div key={l} style={card}><I size={20}/><small style={{display:'block',marginTop:10}}>{l}</small><strong style={{fontSize:22}}>{v}</strong></div>)}</div>
 <section style={{...card,marginBottom:18}}><h2 style={{marginTop:0}}>💸 Retirer mes gains</h2><p style={{color:'#666'}}>Minimum 5 000 FCFA. Le solde est débité immédiatement à la demande puis le retrait reste en attente de traitement.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10}}><input value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,''))} inputMode="numeric" placeholder="Montant en FCFA"/><select value={method} onChange={e=>setMethod(e.target.value)}><option value="mtn_momo">MTN Mobile Money</option><option value="orange_money">Orange Money</option><option value="wave">Wave</option></select><input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="6XXXXXXXX"/></div><button onClick={requestPayout} disabled={payoutLoading} style={{marginTop:12,display:'inline-flex',alignItems:'center',gap:8,padding:'12px 18px',border:0,borderRadius:10,background:'#f97316',color:'#fff',fontWeight:800}}>{payoutLoading?<Loader2 className="spin" size={17}/>:<Banknote size={17}/>} {payoutLoading?'Traitement...':'Demander le retrait'}</button></section>
 <section style={{...card,marginBottom:18}}><h2 style={{marginTop:0}}>Historique des retraits</h2>{payouts.length?<div style={{display:'grid',gap:8}}>{payouts.map(p=><div key={p.id} style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:10,padding:12,borderRadius:10,background:'#f8f9fb'}}><div><b>{money(p.amount)}</b><small style={{display:'block',color:'#777'}}>{p.method} · {p.phone_number}</small></div><span>{p.status}</span><small>{new Date(p.requested_at).toLocaleDateString('fr-FR')}</small></div>)}</div>:<p style={{color:'#777'}}>Aucun retrait demandé.</p>}</section>
 <section style={card}><h2 style={{margin:0}}>🏆 Classement des affiliés</h2><p style={{color:'#666'}}>Les ventes validées déterminent le classement.</p><div style={{display:'flex',gap:8,margin:'18px 0',flexWrap:'wrap'}}>{periods.map(([p,l])=><button key={p} onClick={()=>setPeriod(p)} style={{padding:'9px 13px',borderRadius:20,border:'1px solid #ddd',background:period===p?'#111827':'#fff',color:period===p?'#fff':'#111',cursor:'pointer'}}>{l}</button>)}</div>{loading?<p>Chargement...</p>:ranking.length?<div style={{display:'grid',gap:8}}>{ranking.map(r=><div key={r.affiliate_id} style={{display:'grid',gridTemplateColumns:'55px 1fr auto auto',gap:10,alignItems:'center',padding:14,borderRadius:12,background:r.affiliate_id===affiliate.id?'#fff7ed':'#f8f9fb',border:r.affiliate_id===affiliate.id?'1px solid #f59e0b':'1px solid transparent'}}><strong style={{fontSize:20}}>{r.rank<=3?['🥇','🥈','🥉'][r.rank-1]:`#${r.rank}`}</strong><div><b>{r.affiliate_code}{r.affiliate_id===affiliate.id?' · Vous':''}</b><small style={{display:'block',color:'#777'}}>{r.sales_count} vente(s) · {r.clicks} clic(s)</small></div><strong>{money(r.sales_amount)}</strong><span>{money(r.commission_amount)}</span></div>)}</div>:<p>Aucun affilié classé pour cette période.</p>}{me&&<div style={{marginTop:16,padding:14,borderRadius:12,background:'#f3f4f6'}}>Votre position : <b>#{me.rank}</b> · {me.sales_count} vente(s) · {money(me.sales_amount)} générés.</div>}</section></>}
 </div></div>}
