import React,{useState}from'react';
import{LogIn,UserPlus,Mail,X}from'lucide-react';
import{supabase}from'./lib/supabase';
import'./marketplace-topnav.css';
export default function AuthModal({mode='login',onClose,onSuccess,onSignup}){
 const[tab,setTab]=useState(mode==='signup'?'signup':'login');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 async function login(e){e.preventDefault();setBusy(true);setMsg('');const{data,error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error)setMsg(error.message);else{onSuccess?.(data.session);onClose?.()}setBusy(false)}
 async function signup(e){e.preventDefault();setBusy(true);setMsg('');const{data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password});if(error)setMsg(error.message);else{setMsg(data.session?'Compte créé avec succès.':'Compte créé. Vérifiez votre e-mail pour confirmer votre compte.');if(data.session){onSignup?.(data.user);onClose?.()}}setBusy(false)}
 const switchTab=t=>{setTab(t);setMsg('');setEmail('');setPassword('')};
 return <div className="pjd-flow-backdrop"><div className="pjd-flow" role="dialog" aria-modal="true"><button className="pjd-flow-close"onClick={onClose}aria-label="Fermer"><X/></button><div className="pjd-auth-tabs"><button type="button" className={tab==='login'?'pjd-primary':'pjd-secondary'} onClick={()=>switchTab('login')}><LogIn/> <span>Se connecter</span></button><button type="button" className={tab==='signup'?'pjd-primary':'pjd-secondary'} onClick={()=>switchTab('signup')}><UserPlus/> <span>S’inscrire</span></button></div>{tab==='login'?<><div className="pjd-flow-title"><LogIn/><span>Connexion</span></div><h2>Se connecter</h2><p>Bienvenue sur PJD Maker. Connectez-vous à votre compte.</p><form onSubmit={login}><label>E-mail<input type="email"value={email}onChange={e=>setEmail(e.target.value)}autoComplete="email"required/></label><label>Mot de passe<input type="password"value={password}onChange={e=>setPassword(e.target.value)}autoComplete="current-password"required/></label><button type="submit"className="pjd-primary pjd-auth-submit"disabled={busy}><LogIn/><span>{busy?'Connexion...':'Se connecter'}</span></button></form></>:<><div className="pjd-flow-title"><UserPlus/><span>Inscription</span></div><h2>S’inscrire</h2><p>Créez votre compte PJD Maker. Vous serez redirigé vers l’accueil du PJD Market après l’inscription.</p><form onSubmit={signup}><label>E-mail<input type="email"value={email}onChange={e=>setEmail(e.target.value)}autoComplete="email"required/></label><label>Mot de passe<input type="password"value={password}onChange={e=>setPassword(e.target.value)}autoComplete="new-password"minLength={6}required/></label><button type="submit"className="pjd-primary pjd-auth-submit"disabled={busy}><UserPlus/><span>{busy?'Inscription...':'S’inscrire'}</span></button></form></>}{msg&&<div className="pjd-flow-msg">{msg}</div>}<button type="button"className="pjd-secondary pjd-auth-switch"onClick={()=>switchTab(tab==='login'?'signup':'login')}>{tab==='login'?'Pas encore de compte ? S’inscrire':'Déjà un compte ? Se connecter'}</button></div></div>;
}