import React,{useState}from'react';
import{LogIn,UserPlus,Mail,X}from'lucide-react';
import{supabase}from'./lib/supabase';
import'./marketplace-topnav.css';

export default function AuthModal({mode='login',onClose,onSuccess,onSignup}){
 const[tab,setTab]=useState(mode==='signup'?'signup':'login');
 const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 async function login(e){e.preventDefault();setBusy(true);setMsg('');const{data,error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error)setMsg(error.message);else{onSuccess?.(data.session);onClose?.()}setBusy(false)}
 async function signup(e){e.preventDefault();setBusy(true);setMsg('');const{data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password});if(error)setMsg(error.message);else{setMsg(data.session?'Compte créé avec succès.':'Compte créé. Vérifiez votre e-mail pour confirmer votre compte.');if(data.session){onSuccess?.(data.session);onClose?.()}}setBusy(false)}
 return <div className="pjd-flow-backdrop"><div className="pjd-flow"><button className="pjd-flow-close"onClick={onClose}><X/></button><div style={{display:'flex',gap:8,marginBottom:18}}><button type="button" className={tab==='login'?'pjd-primary':'pjd-secondary'} onClick={()=>{setTab('login');setMsg('')}}><LogIn/> Se connecter</button><button type="button" className={tab==='signup'?'pjd-primary':'pjd-secondary'} onClick={()=>{setTab('signup');setMsg('')}}><UserPlus/> S'inscrire</button></div>{tab==='login'?<><div className="pjd-flow-title"><LogIn/><span>Connexion</span></div><h2>Bienvenue sur PJD Maker</h2><p>Connectez-vous à votre compte.</p><form onSubmit={login}><label>E-mail<input type="email"value={email}onChange={e=>setEmail(e.target.value)}autoComplete="email"required/></label><label>Mot de passe<input type="password"value={password}onChange={e=>setPassword(e.target.value)}autoComplete="current-password"required/></label><button className="pjd-primary"disabled={busy}>{busy?'Connexion...':'Se connecter'}</button></form><button type="button"className="pjd-secondary"onClick={()=>setMsg('Utilisez la récupération de mot de passe configurée dans votre compte Supabase.')}>Mot de passe oublié ?</button></>:<><div className="pjd-flow-title"><UserPlus/><span>Inscription</span></div><h2>Créez votre compte</h2><p>Créez votre compte PJD Maker. La boutique se crée séparément.</p><form onSubmit={signup}><label>E-mail<input type="email"value={email}onChange={e=>setEmail(e.target.value)}autoComplete="email"required/></label><label>Mot de passe<input type="password"value={password}onChange={e=>setPassword(e.target.value)}autoComplete="new-password"minLength={6}required/></label><button className="pjd-primary"disabled={busy}>{busy?'Création...':'Créer mon compte'}</button></form></>}{msg&&<div className="pjd-flow-msg">{msg}</div>}<button type="button"className="pjd-secondary"onClick={()=>tab==='login'?onSignup?.():setTab('login')}>{tab==='login'?'Créer un compte':'J’ai déjà un compte'}</button></div></div>;
}
