import React,{useEffect,useState}from'react';
import{PackageCheck,RefreshCw,Star}from'lucide-react';
import{supabase}from'./lib/supabase';
const money=v=>`${Number(v||0).toLocaleString('fr-FR')} FCFA`;
const labels={pending:'En attente',confirmed:'Confirmée',processing:'En préparation',shipped:'Expédiée',delivered:'Livrée',cancelled:'Annulée'};
const steps=['pending','confirmed','processing','shipped','delivered'];
export default function CustomerOrders({session,onBack}){
 const[orders,setOrders]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const load=async()=>{if(!session?.user?.id)return;setLoading(true);setError('');try{const{data,error}=await supabase.from('orders').select('id,total,status,payment_method,created_at,order_items(id,name,price,quantity,shop_id,seller_id),deliveries(id,status,delivery_address,fee,delivered_at)').eq('user_id',session.user.id).order('created_at',{ascending:false});if(error)throw error;setOrders(data||[])}catch(e){setError(e.message||'Impossible de charger vos commandes.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[session?.user?.id]);
 return <div style={{minHeight:'100vh',background:'#f7f8fb',padding:20,fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1000,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:18}}><div><h1 style={{margin:0,color:'#101b2d'}}>Mes commandes</h1><p style={{color:'#667085'}}>Suivez vos achats et leurs livraisons.</p></div><button onClick={onBack} style={btn}>Retour</button></div>{error&&<div style={err}>{error}</div>}{loading?<div style={card}>Chargement…</div>:orders.length===0?<div style={{...card,textAlign:'center'}}>Aucune commande pour le moment.</div>:orders.map(o=>{const idx=steps.indexOf(o.status);return <article key={o.id} style={card}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><b>Commande #{String(o.id).slice(0,8)}</b><div style={{color:'#667085',fontSize:13}}>{new Date(o.created_at).toLocaleString('fr-FR')} · {o.payment_method||'Paiement'}</div></div><strong>{money(o.total)}</strong></div><div style={{display:'flex',gap:5,margin:'16px 0 10px'}}>{steps.map((s,i)=><div key={s} style={{flex:1,height:7,borderRadius:9,background:i<=idx?'#f97316':'#e4e7ec'}}/>)}</div><b>{labels[o.status]||o.status}</b><div style={{marginTop:12,display:'grid',gap:7}}>{(o.order_items||[]).map(i=><div key={i.id} style={{display:'flex',justifyContent:'space-between',borderTop:'1px solid #eee',paddingTop:8}}><span>{i.name} × {i.quantity}</span><span>{money(Number(i.price)*Number(i.quantity))}</span></div>)}</div>{(o.deliveries||[]).map(d=><div key={d.id} style={{marginTop:12,padding:10,borderRadius:10,background:'#f2f4f7'}}><PackageCheck size={16} style={{verticalAlign:'middle'}}/> Livraison : <b>{labels[d.status]||d.status}</b>{d.delivery_address&&<div style={{fontSize:13,color:'#667085'}}>{d.delivery_address}</div>}</div>)}</article>})}<button onClick={load} style={{...btn,marginTop:14}}><RefreshCw size={15}/> Actualiser</button></div></div>}
const card={background:'#fff',border:'1px solid #e4e7ec',borderRadius:14,padding:16,marginBottom:12};const btn={border:0,borderRadius:10,padding:'10px 14px',background:'#16233f',color:'#fff',fontWeight:800,display:'inline-flex',gap:7,alignItems:'center'};const err={background:'#fff1f0',color:'#b42318',padding:12,borderRadius:10,marginBottom:12};