import React,{useEffect,useState}from'react';
import{Heart,ArrowLeft,ShoppingCart,Download,Trash2,Store}from'lucide-react';
import{supabase}from'./lib/supabase';

export default function FavoritesPage({onBack}){
 const[favorites,setFavorites]=useState([]),[loading,setLoading]=useState(true);
 useEffect(()=>{try{setFavorites(JSON.parse(localStorage.getItem('pjd-favorites')||'[]'))}catch{setFavorites([])}setLoading(false)},[]);
 function remove(p){const next=favorites.filter(x=>x.id!==p.id);setFavorites(next);localStorage.setItem('pjd-favorites',JSON.stringify(next));}
 async function download(p){if(!p.file_url)return alert('Le fichier de ce produit n’est pas encore disponible.');let url=p.file_url;if(!/^https?:\/\//i.test(url)){const r=await supabase.storage.from('product-files').createSignedUrl(url,3600);if(r.error||!r.data?.signedUrl)return alert('Impossible de préparer le téléchargement.');url=r.data.signedUrl}window.open(url,'_blank','noopener,noreferrer');}
 return <div className="fav-page"><header><button onClick={onBack}><ArrowLeft size={17}/> Marketplace</button><div><span>VOS SÉLECTIONS</span><h1>Mes favoris</h1></div></header>{loading?<p>Chargement...</p>:!favorites.length?<div className="fav-empty"><Heart size={42}/><h2>Aucun favori</h2><p>Ajoutez des produits avec le cœur pour les retrouver ici.</p><button onClick={onBack}>Découvrir les produits</button></div>:<div className="fav-grid">{favorites.map(p=>{const free=Boolean(p.is_free)||Number(p.price||0)===0;return <article key={p.id}><div className="fav-img">{p.cover_image||p.image_url?<img src={p.cover_image||p.image_url} alt=""/>:<Store size={35}/>}</div><div className="fav-body"><small>{p.category||'Produit'}</small><h3>{p.title}</h3><strong>{free?'Gratuit':`${Number(p.promo_price??p.price).toLocaleString('fr-FR')} FCFA`}</strong><div><button onClick={()=>free?download(p):document.dispatchEvent(new CustomEvent('pjd-add-to-cart',{detail:p}))}>{free?<><Download size={15}/> Télécharger</>:<><ShoppingCart size={15}/> Ajouter au panier</>}</button><button className="remove" onClick={()=>remove(p)}><Trash2 size={15}/></button></div></div></article>})}</div>}<style>{`.fav-page{max-width:1180px;margin:auto;padding:30px 18px 70px}.fav-page header{display:flex;gap:22px;align-items:center;margin-bottom:30px}.fav-page header button{border:1px solid #ddd;background:#fff;border-radius:10px;padding:10px 13px;display:flex;gap:7px;align-items:center;cursor:pointer}.fav-page header span{font-size:10px;font-weight:800;letter-spacing:.14em;color:#888}.fav-page h1{margin:5px 0;font-size:34px}.fav-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.fav-grid article{border:1px solid #e5e7ea;border-radius:17px;overflow:hidden;background:#fff}.fav-img{height:190px;background:#f2f3f5;display:grid;place-items:center}.fav-img img{width:100%;height:100%;object-fit:cover}.fav-body{padding:15px}.fav-body small{color:#888}.fav-body h3{margin:7px 0 12px;font-size:16px}.fav-body strong{display:block;margin-bottom:13px}.fav-body div{display:flex;gap:7px}.fav-body button{border:0;background:#151515;color:#fff;border-radius:9px;padding:9px 11px;display:flex;align-items:center;gap:6px;cursor:pointer;flex:1;justify-content:center}.fav-body button.remove{flex:0;background:#f1f2f4;color:#444}.fav-empty{text-align:center;padding:80px 20px;border:1px dashed #d8dadd;border-radius:20px}.fav-empty button{background:#151515;color:#fff;border:0;border-radius:10px;padding:11px 16px}.fav-empty svg{opacity:.45}@media(max-width:900px){.fav-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.fav-grid{grid-template-columns:1fr}.fav-page header{align-items:flex-start;flex-direction:column}}`}</style></div>;
}