import React,{useEffect,useState}from'react';
import{Heart,ShoppingCart,Store,User,Mail,X,UserPlus}from'lucide-react';
import{supabase}from'./lib/supabase';
import'./marketplace-topnav.css';

export default function MarketplaceTopNav({session,onOpenCart,onOpenSeller,onOpenAccount}){
 const[shop,setShop]=useState(null);
 useEffect(()=>{let alive=true;if(!session){setShop(null);return()=>{alive=false}};supabase.from('shops').select('*').eq('owner_id',session.user.id).limit(1).maybeSingle().then(({data})=>{if(alive)setShop(data||null)});const handler=e=>setShop(e.detail||null);window.addEventListener('pjd-shop-updated',handler);return()=>{alive=false;window.removeEventListener('pjd-shop-updated',handler)}},[session?.user?.id]);
 const openShop=()=>{if(shop){window.dispatchEvent(new CustomEvent('pjd-open-shop',{detail:{shopId:shop.id,shop}}));return}onOpenSeller?.(null)};
 return <div className="pjd-topnav"><div className="pjd-topnav-brand"><b>PJD</b><span>MAKER</span></div><div className="pjd-topnav-actions">{session?<><button className="pjd-action"onClick={()=>onOpenAccount?.('favorites')}><Heart/><span>Favoris</span></button><button className="pjd-action"onClick={onOpenCart}><ShoppingCart/><span>Panier</span></button><button className="pjd-action pjd-shop"onClick={openShop}><Store/><span>{shop?'Ma boutique':'Créer ma boutique'}</span></button><button className="pjd-action"onClick={()=>onOpenAccount?.('account')}><User/><span>Mon compte</span></button></>:<button className="pjd-action pjd-create-shop"onClick={()=>onOpenSeller?.(null)}><UserPlus/><span>S'inscrire</span></button>}</div></div>;
}

export function CreateShopFlow({session,onDone,onClose}){
 const[mode,setMode]=useState(session?'checking':'signup'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[activeSession,setActiveSession]=useState(session),[form,setForm]=useState({name:'',category:'',description:'',phone:'',city:'',country:'Cameroun'});
 const openExisting=async(shop)=>{await supabase.from('users').update({role:'vendeur',shop_id:shop.id}).eq('id',shop.owner_id);window.dispatchEvent(new CustomEvent('pjd-shop-updated',{detail:shop}));window.dispatchEvent(new CustomEvent('pjd-open-shop',{detail:{shopId:shop.id,shop}}));onDone?.(shop);onClose?.()};
 useEffect(()=>{if(!session)return;let alive=true;setActiveSession(session);setBusy(true);supabase.from('shops').select('*').eq('owner_id',session.user.id).limit(1).maybeSingle().then(({data,error})=>{if(!alive)return;setBusy(false);if(error){setMsg(error.message);setMode('shop');return}if(data){openExisting(data);return}setMode('shop');setMsg('Votre compte est connecté. Configurez votre boutique une seule fois.');});return()=>{alive=false}},[session?.user?.id]);
 const update=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function signup(e){e.preventDefault();setBusy(true);setMsg('');const{error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password});if(error)setMsg(error.message);else{setMode('verify');setMsg('Compte créé. Entrez le code de confirmation reçu par e-mail.')}setBusy(false)}
 async function resend(){if(!email)return;setBusy(true);const{error}=await supabase.auth.resend({type:'signup',email:email.trim().toLowerCase()});setMsg(error?error.message:'Un nouveau code vient d’être envoyé.');setBusy(false)}
 async function verify(e){e.preventDefault();if(code.length!==8){setMsg('Le code doit contenir exactement 8 chiffres.');return}setBusy(true);setMsg('');const{data,error}=await supabase.auth.verifyOtp({email:email.trim().toLowerCase(),token:code,type:'signup'});if(error)setMsg(error.message);else{setActiveSession(data.session);const existing=await supabase.from('shops').select('*').eq('owner_id',data.session.user.id).limit(1).maybeSingle();if(existing.data){await openExisting(existing.data)}else{setMode('shop');setMsg('Compte confirmé. Configurez votre boutique une seule fois.')}}setBusy(false)}
 async function saveShop(e){e.preventDefault();if(!activeSession)return;setBusy(true);setMsg('');const existing=await supabase.from('shops').select('*').eq('owner_id',activeSession.user.id).limit(1).maybeSingle();if(existing.error){setMsg(existing.error.message);setBusy(false);return}if(existing.data){await openExisting(existing.data);setBusy(false);return}const slug=form.name.toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+activeSession.user.id.slice(0,6);const{data,error}=await supabase.from('shops').insert({owner_id:activeSession.user.id,shop_name:form.name.trim(),slug,description:form.description.trim(),category:form.category.trim(),phone:form.phone.trim(),city:form.city.trim(),country:form.country.trim(),status:'active'}).select().single();if(error)setMsg(error.message);else{await supabase.from('users').update({role:'vendeur',shop_id:data.id}).eq('id',activeSession.user.id);window.dispatchEvent(new CustomEvent('pjd-shop-updated',{detail:data}));onDone?.(data);window.dispatchEvent(new CustomEvent('pjd-open-shop',{detail:{shopId:data.id,shop:data}}));onClose?.()}setBusy(false)}
 if(mode==='checking')return <div className="pjd-flow-backdrop"><div className="pjd-flow"><div className="pjd-flow-title"><Store/><span>Ma boutique</span></div><h2>Vérification de votre boutique</h2><p>Nous vérifions votre boutique enregistrée...</p></div></div>;
 return <div className="pjd-flow-backdrop"><div className="pjd-flow"><button className="pjd-flow-close"onClick={onClose}><X/></button>{mode==='signup'&&<><div className="pjd-flow-title"><UserPlus/><span>Inscription</span></div><h2>Créez votre compte</h2><p>Inscrivez-vous pour accéder à votre compte PJD Maker.</p><form onSubmit={signup}><label>E-mail<input type="email"value={email}onChange={e=>setEmail(e.target.value)}required/></label><label>Mot de passe<input type="password"value={password}onChange={e=>setPassword(e.target.value)}minLength={6}required/></label><button className="pjd-primary"disabled={busy}>Créer mon compte</button></form></>}{mode==='verify'&&<><div className="pjd-flow-title"><Mail/><span>Vérification</span></div><h2>Confirmez votre e-mail</h2><p>Entrez le code à 8 chiffres reçu à <b>{email}</b>.</p><form onSubmit={verify}><input className="pjd-code"inputMode="numeric"maxLength={8}minLength={8}pattern="[0-9]{8}"value={code}onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,8))}placeholder="00000000"required/><button className="pjd-primary"disabled={busy||code.length!==8}>Continuer</button></form><button type="button"className="pjd-secondary"onClick={resend}disabled={busy}>Renvoyer le code</button></>}{mode==='shop'&&<><div className="pjd-flow-title"><Store/><span>Créer ma boutique</span></div><h2>Configurez votre boutique</h2><p>Ces informations sont enregistrées une seule fois. Une boutique existante sera ouverte automatiquement.</p><form onSubmit={saveShop}><label>Nom de la boutique *<input value={form.name}onChange={e=>update('name',e.target.value)}required/></label><label>Catégorie *<input value={form.category}onChange={e=>update('category',e.target.value)}required/></label><label>Description<textarea value={form.description}onChange={e=>update('description',e.target.value)}rows={3}/></label><div className="pjd-two"><label>Téléphone<input value={form.phone}onChange={e=>update('phone',e.target.value)}/></label><label>Ville<input value={form.city}onChange={e=>update('city',e.target.value)}/></label></div><button className="pjd-primary"disabled={busy}>Créer ma boutique</button></form></>}{msg&&<div className="pjd-flow-msg">{msg}</div>}</div></div>;
}
