import React,{useEffect,useMemo,useRef,useState}from'react';
import{BookOpen,Download,Loader2,Pause,Play,RotateCcw,Volume2,Lock,Clock,ShoppingCart}from'lucide-react';
import{supabase}from'./lib/supabase';
const getKind=p=>{const t=String(p?.file_type||'').toLowerCase(),c=String(p?.category||'').toLowerCase(),title=String(p?.title||'').toLowerCase();if(t.startsWith('audio/')||c.includes('audio')||c.includes('musique')||title.includes('audiobook')||title.includes('livre audio'))return'audio';if(t.startsWith('video/'))return'video';if(t==='application/pdf'||t.includes('pdf')||/\.pdf$/i.test(String(p?.file_url||'')))return'pdf';if(t.includes('epub')||/\.epub$/i.test(String(p?.file_url||'')))return'ebook';return'file'};
const fmt=s=>{s=Math.max(0,Math.floor(Number(s)||0));const m=Math.floor(s/60),h=Math.floor(m/60),mm=m%60,ss=String(s%60).padStart(2,'0');return h?(h+':'+String(mm).padStart(2,'0')+':'+ss):(mm+':'+ss)};
const isPaid=p=>!Boolean(p?.is_free)&&Number(p?.promo_price??p?.price??0)>0;
export default function MediaPlayer({product,onBuy}){
 const kind=useMemo(()=>getKind(product),[product]),ref=useRef(null),key='pjd-media-progress:'+(product?.id||'');
 const[ url,setUrl]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[current,setCurrent]=useState(()=>Number(localStorage.getItem(key)||0)),[duration,setDuration]=useState(0),[preview,setPreview]=useState(false),[previewEnded,setPreviewEnded]=useState(false);
 const paid=isPaid(product),audioPreviewLimit=30;
 useEffect(()=>{setUrl('');setError('');setPlaying(false);setPreview(false);setPreviewEnded(false);setCurrent(Number(localStorage.getItem(key)||0));setDuration(0)},[product?.id,key]);
 async function openMedia(){if(url){return ref.current?.play?.().catch(()=>{})}setLoading(true);setError('');try{const{data:session}=await supabase.auth.getSession();if(!session?.session?.user){window.dispatchEvent(new CustomEvent('pjd-require-auth',{detail:{action:'media',product}}));return}let r=await supabase.functions.invoke('media-access',{body:{product_id:product.id}});if((r.error||!r.data?.signed_url)&&kind==='audio'&&paid)r=await supabase.functions.invoke('media-access',{body:{product_id:product.id,preview_only:true}});if(r.error||!r.data?.signed_url)throw new Error(r.data?.error||'Contenu indisponible. Après un achat, l’accès est activé automatiquement.');setPreview(Boolean(r.data?.preview_only)&&kind==='audio');setPreviewEnded(false);setUrl(r.data.signed_url);if(r.data.event_type==='listen'){try{await supabase.rpc('track_pjd_content_event',{p_product_id:product.id,p_event_type:'listen',p_visitor_id:localStorage.getItem('pjd-visitor-id')||null})}catch{}}}catch(e){setError(e?.message||'Impossible de charger ce contenu.')}finally{setLoading(false)}}
 function onLoaded(e){const d=Number(e.currentTarget.duration)||0;setDuration(d);if(kind==='audio'&&preview){e.currentTarget.currentTime=0;return}const p=Number(localStorage.getItem(key)||0);if(p>0&&p<d)e.currentTarget.currentTime=p}
 function stopPreview(){if(!ref.current)return;ref.current.pause();ref.current.currentTime=Math.min(audioPreviewLimit,Number(ref.current.duration)||audioPreviewLimit);setCurrent(audioPreviewLimit);setPlaying(false);setPreviewEnded(true)}
 function onTime(e){const t=Number(e.currentTarget.currentTime)||0;if(kind==='audio'&&preview&&t>=audioPreviewLimit){stopPreview();return}setCurrent(t);if(!preview&&Math.floor(t)%5===0)localStorage.setItem(key,String(t))}
 function onSeeking(e){if(kind==='audio'&&preview&&Number(e.currentTarget.currentTime)>audioPreviewLimit)e.currentTarget.currentTime=audioPreviewLimit}
 function onEnded(){setPlaying(false);if(preview)setPreviewEnded(true);else localStorage.removeItem(key)}
 if(!product?.id||kind==='file')return null;
 if(kind==='pdf'||kind==='ebook'){const previewImage=product?.pdf_preview_url||product?.preview_url||product?.cover_image||product?.image_url;return <div className="pjd-media-card"><div className="pjd-media-head"><div><span className="pjd-media-kicker">LECTURE</span><h3><BookOpen size={18}/>Première page</h3></div><span className="pjd-media-lock"><Lock size={15}/> Aperçu gratuit</span></div>{previewImage?<div className="pjd-book-preview-single"><img src={previewImage}alt={'Première page de '+(product.title||'ce livre')}/></div>:<div className="pjd-media-error">La première page de ce PDF n’est pas encore disponible.</div>}<p className="pjd-media-help">Vous pouvez lire uniquement la première page. Le livre complet est accessible après achat et téléchargement.</p>{paid&&<button className="pjd-media-buy"onClick={()=>onBuy?.(product)}><ShoppingCart size={17}/>Acheter pour lire le livre complet</button>}</div>}
 return <div className="pjd-media-card"><div className="pjd-media-head"><div><span className="pjd-media-kicker">AUDIO</span><h3><Volume2 size={18}/>Écouter maintenant</h3></div>{preview&&<span className="pjd-media-lock"><Clock size={15}/> Aperçu 30 secondes</span>}</div>{url&&<><audio ref={ref}src={url}controls preload="metadata"onLoadedMetadata={onLoaded}onTimeUpdate={onTime}onSeeking={onSeeking}onPlay={()=>setPlaying(true)}onPause={()=>setPlaying(false)}onEnded={onEnded}/><div className="pjd-media-progress"><span>{fmt(current)}</span><span>{fmt(preview?audioPreviewLimit:duration)}</span></div>{preview&&<div className="pjd-media-preview-limit"><Lock size={14}/> L’introduction est limitée à 30 secondes.</div>}{!preview&&<button className="pjd-reset-btn"onClick={()=>{localStorage.removeItem(key);setCurrent(0);if(ref.current)ref.current.currentTime=0}}><RotateCcw size={14}/>Reprendre depuis le début</button>}{preview&&previewEnded&&<button className="pjd-media-buy"onClick={()=>onBuy?.(product)}><ShoppingCart size={17}/>Payer et télécharger pour continuer l’écoute</button>}</>}{!url&&<button className="pjd-media-main-btn"onClick={openMedia}disabled={loading}>{loading?<Loader2 className="pjd-spin"/>:<Play size={18}/>} {loading?'Chargement...':paid?'Écouter l’introduction':'Écouter'}</button>}{error&&<p className="pjd-media-error">{error}</p>}<p className="pjd-media-download-note"><Download size={14}/>{preview?'Après paiement, le fichier audio complet peut être téléchargé et écouté sans cette limite.':'Le fichier audio complet est accessible après achat.'}</p></div>
}