import React,{useEffect,useState}from'react';import{supabase}from'./lib/supabase';
const providers=[['facebook','📘','Facebook','/api/social/oauth/facebook'],['instagram','📸','Instagram','/api/social/oauth/instagram'],['tiktok','🎵','TikTok','/api/social/oauth/tiktok'],['youtube','▶️','YouTube','/api/social/oauth/youtube'],['whatsapp','💬','WhatsApp','/api/social/oauth/whatsapp'],['telegram','✈️','Telegram','/api/social/oauth/telegram']];
export default function PromotionSocialPanel({session}){const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[selected,setSelected]=useState([]),[notice,setNotice]=useState('');
 const save=async(list)=>{setSelected(list);if(session?.user?.id){const{error}=await supabase.rpc('set_social_promotion_preferences',{p_providers:list});if(error)setNotice(error.message)}};
 const load=async()=>{if(!session?.user?.id){setLoading(false);return}const{data,error}=await supabase.from('social_connections').select('provider,account_name,status,updated_at').eq('user_id',session.user.id);if(error)setNotice(error.message);const r=data||[];setRows(r);const connected=r.filter(x=>x.status==='connected').map(x=>x.provider);setSelected(connected);if(connected.length)await supabase.rpc('set_social_promotion_preferences',{p_providers:connected});setLoading(false)};
 useEffect(()=>{load()},[session?.user?.id]);
 const row=p=>rows.find(x=>x.provider===p),connected=providers.filter(([id])=>row(id)?.status==='connected');
 const connect=async(id,url)=>{setBusy(id);setNotice('');try{const{data:s}=await supabase.auth.getSession();const token=s?.session?.access_token;if(!token)throw new Error('Session PJD Market expirée, reconnectez-vous.');const r=await fetch(url,{credentials:'include',headers:{Authorization:`Bearer ${token}`}});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||'OAuth non configuré pour ce réseau')}const j=await r.json();if(j.url)window.location.href=j.url;else throw new Error(j.error||'Lien de connexion indisponible')}catch(e){setNotice(`${id}: ${e.message}`)}finally{setBusy('')}};
 const toggle=id=>save(selected.includes(id)?selected.filter(v=>v!==id):[...selected,id]);
 const continuePromotion=async()=>{await save(selected);window.dispatchEvent(new CustomEvent('pjd:promotion-social-selection',{detail:{providers:selected}}));const el=document.querySelector('[data-pjd-promotion-form]');if(el)el.scrollIntoView({behavior:'smooth',block:'start'});};
 return <div data-pjd-social-panel style={{padding:14,border:'1px solid #e5e7eb',borderRadius:14,background:'#f8fafc',marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8,flexWrap:'wrap'}}><div><b>🌐 Publication sur les réseaux sociaux</b><div style={{fontSize:12,color:'#667085',marginTop:3}}>Choisissez les comptes qui recevront cette promotion après sa création.</div></div><strong style={{color:connected.length?'#16a34a':'#667085'}}>{loading?'…':`${connected.length}/6 réseaux connectés`}</strong></div>{notice&&<div style={{marginTop:10,padding:10,borderRadius:10,background:'#fff7ed',border:'1px solid #fed7aa',fontSize:12}}>{notice}</div>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:8,marginTop:10}}>{providers.map(([id,icon,name,url])=>{const r=row(id),ok=r?.status==='connected',checked=selected.includes(id);return <div key={id} style={{padding:10,borderRadius:11,border:ok?(checked?'2px solid #16a34a':'1px solid #86efac'):'1px solid #e5e7eb',background:ok?'#f0fdf4':'#fff'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:8}}><b>{icon} {name}</b>{ok?<label style={{fontSize:12,fontWeight:800,cursor:'pointer'}}><input type="checkbox" checked={checked} onChange={()=>toggle(id)}/> Publier</label>:<button type="button" disabled={busy===id} onClick={()=>connect(id,url)} style={{padding:'7px 10px',border:0,borderRadius:8,background:'#111',color:'#fff',fontWeight:800}}>{busy===id?'Connexion…':'Connecter'}</button>}</div><small style={{display:'block',color:ok?'#15803d':'#667085',marginTop:4}}>{ok?`✓ Connecté${r.account_name?` · ${r.account_name}`:''}`:'Non synchronisé'}</small></div>})}</div><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,flexWrap:'wrap',marginTop:12}}><small style={{color:'#667085'}}>{selected.length?`${selected.length} réseau(x) sélectionné(s) pour cette promotion.`:'Aucun réseau sélectionné.'}</small><button type="button" onClick={continuePromotion} style={{padding:'11px 16px',border:0,borderRadius:10,background:selected.length?'#16a34a':'#111',color:'#fff',fontWeight:900,cursor:'pointer'}}>Continuer la promotion →</button></div><small style={{display:'block',color:'#667085',marginTop:8}}>La connexion passe par l’autorisation officielle du réseau. Aucun token n’est demandé dans l’interface PJD Market.</small></div>}
