import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,Store,ShoppingCart,Loader2,Image as ImageIcon,Bell,BellOff,Star,Send,Trash2,Users,Package,FileText,Gift,Tag}from'lucide-react';
import{supabase}from'./lib/supabase';
import'./public-shop.css';

const statuses=['active','approved','actif','approuvé'];
const money=v=>Number(v||0)===0?'Gratuit':`${Number(v||0).toLocaleString('fr-FR')} FCFA`;
const isUuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
const imageOf=p=>{if(p?.cover_image)return p.cover_image;if(p?.image_url)return p.image_url;if(Array.isArray(p?.images))return p.images[0]||'';if(typeof p?.images==='string'){try{const x=JSON.parse(p.images);return Array.isArray(x)?x[0]||'':''}catch{return p.images}}return''};
function Stars({value=0,interactive=false,onChange,size=17}){const n=Math.round(Number(value)||0);return <div className="shop-stars">{[1,2,3,4,5].map(s=><button key={s} type={interactive?'button':undefined} className={`shop-star ${s<=n?'active':''} ${interactive?'interactive':''}`} onClick={()=>interactive&&onChange?.(s)}><Star size={size} fill={s<=n?'currentColor':'none'}/></button>)}</div>}

export default function PublicShopPage({shopId,onBack,onAdd}){
 const[shop,setShop]=useState(null),[products,setProducts]=useState([]),[shopReviews,setShopReviews]=useState([]),[productReviews,setProductReviews]=useState([]),[user,setUser]=useState(null),[following,setFollowing]=useState(false),[followerCount,setFollowerCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('all'),[reviewProduct,setReviewProduct]=useState(null),[reviewRating,setReviewRating]=useState(5),[reviewComment,setReviewComment]=useState(''),[myProductReviews,setMyProductReviews]=useState({}),[shopReviewOpen,setShopReviewOpen]=useState(false),[shopRating,setShopRating]=useState(5),[shopComment,setShopComment]=useState(''),[myShopReview,setMyShopReview]=useState(null),[followLoading,setFollowLoading]=useState(false);
 const ref=useMemo(()=>{if(shopId)return shopId;const p=window.location.pathname.match(/^\/boutique\/([^/]+)/i);if(p)return decodeURIComponent(p[1]);return new URLSearchParams(window.location.search).get('shop')||''},[shopId]);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user||null));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>data?.subscription?.unsubscribe()},[]);
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);setError('');if(!ref){if(alive){setError('Boutique introuvable');setLoading(false)}return}
  let result;if(isUuid(ref)){result=await supabase.from('shops').select('*').eq('id',ref).maybeSingle();if(!result.data&&!result.error)result=await supabase.from('shops').select('*').eq('owner_id',ref).maybeSingle()}else{result=await supabase.from('shops').select('*').eq('shop_name',ref).maybeSingle()}
  const s=result.data;if(result.error||!s){if(alive){setError('Boutique introuvable');setLoading(false)}return}
  const[d,m]=await Promise.all([supabase.from('digital_products').select('*').eq('shop_id',s.id).in('status',statuses).order('created_at',{ascending:false}),supabase.from('marketplace_products').select('*').eq('shop_id',s.id).eq('status','approved').order('created_at',{ascending:false})]);
  const{count}=await supabase.from('shop_followers').select('id',{count:'exact',head:true}).eq('shop_id',s.id);
  if(alive){setShop(s);setFollowerCount(count??Number(s.followers_count||0));setProducts([...(d.data||[]).map(p=>({...p,product_type:'digital',display_image:imageOf(p)})),...(m.data||[]).map(p=>({...p,product_type:'physical',display_image:imageOf(p)}))]);setLoading(false)}})();return()=>{alive=false}},[ref]);
 useEffect(()=>{if(!shop?.id)return;(async()=>{const{data}=await supabase.from('shop_reviews').select('*').eq('shop_id',shop.id).order('created_at',{ascending:false});setShopReviews(data||[]);if(user){const{data:mine}=await supabase.from('shop_reviews').select('*').eq('shop_id',shop.id).eq('user_id',user.id).maybeSingle();if(mine){setMyShopReview(mine);setShopRating(mine.rating);setShopComment(mine.comment||'')}}const{data:follow}=user?await supabase.from('shop_followers').select('id').eq('shop_id',shop.id).eq('user_id',user.id).maybeSingle():{data:null};setFollowing(!!follow);const{count}=await supabase.from('shop_followers').select('id',{count:'exact',head:true}).eq('shop_id',shop.id);setFollowerCount(count??0)})()},[shop?.id,user]);
 useEffect(()=>{if(!products.length){setProductReviews([]);return}(async()=>{const{data}=await supabase.from('product_reviews').select('*').in('product_id',products.map(p=>p.id)).order('created_at',{ascending:false});setProductReviews(data||[]);if(user){const map={};(data||[]).filter(r=>r.user_id===user.id).forEach(r=>map[r.product_id]=r);setMyProductReviews(map)}})()},[products,user]);
 const filtered=useMemo(()=>products.filter(p=>{const free=Number(p.price||0)===0||p.is_free===true;const promo=p.promo_price!=null&&Number(p.promo_price)<Number(p.price);if(tab==='physical')return p.product_type==='physical';if(tab==='digital')return p.product_type==='digital';if(tab==='free')return free;if(tab==='promo')return promo;return true}),[products,tab]);
 const shopAvg=shopReviews.length?shopReviews.reduce((a,r)=>a+Number(r.rating||0),0)/shopReviews.length:Number(shop?.rating||0);
 const stats=id=>{const r=productReviews.filter(x=>x.product_id===id);return{count:r.length,avg:r.length?r.reduce((a,x)=>a+Number(x.rating||0),0)/r.length:0}};
 const toggleFollow=async()=>{if(!user){alert('Connectez-vous pour vous abonner à cette boutique.');return}setFollowLoading(true);const q=supabase.from('shop_followers');const r=following?await q.delete().eq('shop_id',shop.id).eq('user_id',user.id):await q.insert({shop_id:shop.id,user_id:user.id});if(r.error)alert(r.error.message);else{setFollowing(!following);const{count}=await q.select('id',{count:'exact',head:true}).eq('shop_id',shop.id);setFollowerCount(count??followerCount+(following?-1:1))}setFollowLoading(false)};
 const openReview=p=>{const mine=myProductReviews[p.id];setReviewProduct(p.id);setReviewRating(mine?.rating||5);setReviewComment(mine?.comment||'')};
 const saveReview=async e=>{e.preventDefault();if(!user||!reviewProduct)return;const mine=myProductReviews[reviewProduct];const payload={product_id:reviewProduct,user_id:user.id,rating:Number(reviewRating),comment:reviewComment.trim()};const r=mine?await supabase.from('product_reviews').update({rating:payload.rating,comment:payload.comment,updated_at:new Date().toISOString()}).eq('id',mine.id).eq('user_id',user.id):await supabase.from('product_reviews').insert(payload);if(r.error){alert(r.error.message);return}const{data}=await supabase.from('product_reviews').select('*').in('product_id',products.map(p=>p.id));setProductReviews(data||[]);const map={};(data||[]).filter(x=>x.user_id===user.id).forEach(x=>map[x.product_id]=x);setMyProductReviews(map);setReviewProduct(null)};
 const deleteReview=async p=>{const mine=myProductReviews[p.id];if(!mine||!confirm('Supprimer votre avis sur ce produit ?'))return;const r=await supabase.from('product_reviews').delete().eq('id',mine.id).eq('user_id',user.id);if(!r.error){setProductReviews(x=>x.filter(r=>r.id!==mine.id));setMyProductReviews(x=>{const n={...x};delete n[p.id];return n})}else alert(r.error.message)};
 const saveShopReview=async e=>{e.preventDefault();if(!user)return;const r=myShopReview?await supabase.from('shop_reviews').update({rating:Number(shopRating),comment:shopComment.trim(),updated_at:new Date().toISOString()}).eq('id',myShopReview.id).eq('user_id',user.id):await supabase.from('shop_reviews').insert({shop_id:shop.id,user_id:user.id,rating:Number(shopRating),comment:shopComment.trim()});if(r.error){alert(r.error.message);return}const{data}=await supabase.from('shop_reviews').select('*').eq('shop_id',shop.id).order('created_at',{ascending:false});setShopReviews(data||[]);setMyShopReview((data||[]).find(x=>x.user_id===user.id)||null);setShopReviewOpen(false)};
 if(loading)return <main className="public-shop-page"><div className="public-shop-loading"><Loader2 className="spin"/>Chargement de la boutique...</div></main>;
 if(!shop)return <main className="public-shop-page"><div className="public-shop-error"><Store size={42}/><h2>Boutique introuvable</h2><p>La boutique que vous recherchez n'existe pas ou n'est plus disponible sur PJD Market.</p><button className="secondary" onClick={onBack}><ArrowLeft/>Retour</button></div></main>;
 return <main className="public-shop-page"><button className="secondary public-shop-back" onClick={onBack}><ArrowLeft/>Retour à la marketplace</button>
  <section className="public-shop-hero"><div className="public-shop-banner">{shop.banner?<img src={shop.banner} alt="Bannière"/>:<div className="public-shop-banner-empty"><ImageIcon/></div>}<div className="public-shop-logo">{shop.logo?<img src={shop.logo} alt={shop.shop_name}/>:<Store/>}</div></div><div className="public-shop-info centered-shop-info"><span className="eyebrow">BOUTIQUE PJD MARKET</span><h1>{shop.shop_name}</h1><p>{shop.description||'Bienvenue dans cette boutique.'}</p><div className="public-shop-meta"><span>{shop.category||'Marketplace'}</span>{shop.city&&<span>{shop.city}{shop.country?`, ${shop.country}`:''}</span>}</div><div className="public-shop-actions-row"><button className={`shop-follow-button ${following?'following':''}`} onClick={toggleFollow} disabled={followLoading}>{followLoading?<Loader2 size={17} className="spin"/>:following?<BellOff size={17}/>:<Bell size={17}/>} {following?'Se désabonner':"S'abonner"}</button><div className="shop-stat"><Users size={18}/><strong>{Number(followerCount).toLocaleString('fr-FR')}</strong><span>abonnés</span></div><button className="shop-stat shop-stat-button" onClick={()=>{if(!user){alert('Connectez-vous pour donner votre avis.');return}setShopReviewOpen(true)}}><Star size={18} fill="currentColor"/><strong>{shopAvg.toFixed(1)}</strong><span>{shopReviews.length} avis</span></button></div></div></section>
  <section className="section public-shop-products"><div className="section-head"><div><span className="eyebrow">CATALOGUE</span><h2>Produits de {shop.shop_name}</h2><p>{products.length} produit{products.length!==1?'s':''}</p></div></div><div className="product-category-tabs">{[['all','Tous',Package],['physical','Produit physique',ShoppingCart],['digital','Produit numérique',FileText],['free','Produit gratuit',Gift],['promo','Promotion',Tag]].map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={17}/>{label}</button>)}</div><div className="products">{filtered.length?filtered.map(p=>{const free=Number(p.price||0)===0||p.is_free===true;const promo=p.promo_price!=null&&Number(p.promo_price)<Number(p.price);const s=stats(p.id);const mine=myProductReviews[p.id];return <article className="product-card" key={`${p.product_type}-${p.id}`}><div className="product-art">{p.display_image?<img src={p.display_image} alt={p.title} loading="lazy"/>:<Store size={54}/>}<span className={`product-type-badge ${free?'free':promo?'promo':p.product_type}`}>{free?'Produit gratuit':promo?'Promotion':p.product_type==='physical'?'Produit physique':'Produit numérique'}</span></div><div className="product-body"><div className="product-cat">{p.category||'Produit'}</div><h3>{p.title}</h3><p>{p.description||''}</p><div className="product-mini-rating"><Stars value={s.avg}/><span>{s.avg?s.avg.toFixed(1):'Nouveau'} · {s.count} avis</span></div><div className="price"><strong>{money(promo?p.promo_price:p.price)}</strong>{promo&&<del>{money(p.price)}</del>}</div><button className="add" onClick={()=>onAdd?.({...p,source_type:p.product_type})}><ShoppingCart size={17}/>Ajouter au panier</button><div className="product-review-actions"><button onClick={()=>openReview(p)}><Star size={16}/>{mine?'Modifier mon avis':'Donner un avis'}</button>{mine&&<button onClick={()=>deleteReview(p)}><Trash2 size={16}/>Supprimer</button>}</div>{reviewProduct===p.id&&<form className="product-review-form" onSubmit={saveReview}><strong>{mine?'Modifier votre avis':'Votre avis sur ce produit'}</strong><Stars value={reviewRating} interactive onChange={setReviewRating} size={25}/><textarea value={reviewComment} onChange={e=>setReviewComment(e.target.value)} placeholder="Votre expérience avec ce produit..." maxLength={1000} required/><div><button type="button" onClick={()=>setReviewProduct(null)}>Annuler</button><button type="submit"><Send size={16}/>Publier</button></div></form>}</div></article>}) : <div className="empty">Aucun produit dans cette catégorie.</div>}</div></section>
  <section className="section shop-reviews-section"><div className="section-head"><div><span className="eyebrow">AVIS DE LA BOUTIQUE</span><h2>Les clients parlent de {shop.shop_name}</h2><p>{shopReviews.length} avis</p></div><button className="shop-review-button" onClick={()=>{if(!user){alert('Connectez-vous pour donner votre avis.');return}setShopReviewOpen(true)}}><Star size={17}/>{myShopReview?'Modifier mon avis':'Donner mon avis'}</button></div>{shopReviewOpen&&<form className="shop-review-form" onSubmit={saveShopReview}><h3>{myShopReview?'Modifier votre avis':'Donner votre avis sur la boutique'}</h3><Stars value={shopRating} interactive onChange={setShopRating} size={28}/><textarea value={shopComment} onChange={e=>setShopComment(e.target.value)} placeholder="Votre expérience avec cette boutique..." maxLength={1000} required/><div className="shop-review-form-footer"><button type="button" onClick={()=>setShopReviewOpen(false)}>Annuler</button><button type="submit" className="shop-review-submit"><Send size={17}/>Enregistrer</button></div></form>}<div className="shop-rating-summary"><div className="shop-rating-number"><strong>{shopAvg.toFixed(1)}</strong><Stars value={shopAvg}/><span>{shopReviews.length} avis</span></div><div className="shop-rating-text">Avis vérifiés des clients ayant acheté dans cette boutique.</div></div><div className="shop-reviews-list">{shopReviews.length?shopReviews.map(r=><article className="shop-review-card" key={r.id}><div className="shop-review-head"><div className="shop-review-avatar">{String(r.user_id||'?').slice(0,1).toUpperCase()}</div><div><strong>Client</strong><Stars value={r.rating}/></div><span>{r.created_at?new Date(r.created_at).toLocaleDateString('fr-FR'):''}</span></div><p>{r.comment}</p></article>):<div className="empty">Aucun avis pour le moment.</div>}</div></section>
 </main>;
}