import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,Store,ShoppingCart,Loader2,Image as ImageIcon,ShieldCheck,Download,Bell,BellOff,Star,Send,Edit3,Trash2,Users,Package,FileText,Gift,Tag}from'lucide-react';
import{supabase}from'./lib/supabase';
import'./public-shop.css';

const money=v=>Number(v||0)===0?'Gratuit':`${Number(v||0).toLocaleString('fr-FR')} FCFA`;
const statuses=['active','approved','actif','approuvé'];

function Stars({value=0,interactive=false,onChange,size=17}){const n=Math.round(Number(value)||0);return <div className="shop-stars" aria-label={`${value} sur 5`}>{[1,2,3,4,5].map(s=><button key={s} type={interactive?'button':undefined} className={`shop-star ${s<=n?'active':''} ${interactive?'interactive':''}`} onClick={()=>interactive&&onChange?.(s)}><Star size={size} fill={s<=n?'currentColor':'none'}/></button>)}</div>}
function dateFr(v){if(!v)return'';try{return new Date(v).toLocaleDateString('fr-FR',{day:'2-digit',month:'long',year:'numeric'})}catch{return''}}
function imageOf(p){if(p.cover_image)return p.cover_image;if(p.image_url)return p.image_url;if(Array.isArray(p.images))return p.images[0]||'';if(typeof p.images==='string'){try{const x=JSON.parse(p.images);return Array.isArray(x)?x[0]||'':''}catch{return p.images}}return''}
async function freeDownload(p){if(!p.file_url){alert('Le fichier de ce produit gratuit n’est pas encore disponible.');return}try{const r=await fetch(p.file_url);if(!r.ok)throw 0;const b=await r.blob();const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=p.title||'produit';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch{window.open(p.file_url,'_blank','noopener,noreferrer')}}

export default function PublicShopPage({shopId,onBack,onAdd}){
 const[shop,setShop]=useState(null),[products,setProducts]=useState([]),[shopReviews,setShopReviews]=useState([]),[productReviews,setProductReviews]=useState([]),[user,setUser]=useState(null),[following,setFollowing]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('all'),[openProductReview,setOpenProductReview]=useState(null),[reviewLoading,setReviewLoading]=useState(false),[reviewRating,setReviewRating]=useState(5),[reviewComment,setReviewComment]=useState(''),[myProductReviews,setMyProductReviews]=useState({}),[shopReviewOpen,setShopReviewOpen]=useState(false),[shopRating,setShopRating]=useState(5),[shopComment,setShopComment]=useState(''),[myShopReview,setMyShopReview]=useState(null),[followLoading,setFollowLoading]=useState(false),[downloading,setDownloading]=useState(null);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user||null));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>data?.subscription?.unsubscribe()},[]);
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);setError('');const{s,error:se}=await supabase.from('shops').select('*').eq('id',shopId).maybeSingle();if(se||!s){if(alive){setError('Boutique introuvable');setLoading(false)}return}
  const[d,de]=await supabase.from('digital_products').select('*').eq('shop_id',s.id).in('status',statuses).order('created_at',{ascending:false});
  const[m,me]=await supabase.from('marketplace_products').select('*').eq('shop_id',s.id).eq('status','approved').order('created_at',{ascending:false});
  const normalized=[...(d||[]).map(p=>({...p,product_type:'digital',display_image:imageOf(p)})),...(m||[]).map(p=>({...p,product_type:'physical',display_image:imageOf(p)}))];
  if(alive){setShop(s);setProducts(normalized);if(de&&!me)setError(de.message);setLoading(false)}})();return()=>{alive=false}},[shopId]);
 const productIds=useMemo(()=>products.map(p=>p.id),[products]);
 useEffect(()=>{if(!shopId)return;(async()=>{const{data:srv}=await supabase.from('shop_reviews').select('*').eq('shop_id',shopId).order('created_at',{ascending:false});setShopReviews(srv||[]);if(user){const{data:mine}=await supabase.from('shop_reviews').select('*').eq('shop_id',shopId).eq('user_id',user.id).maybeSingle();if(mine){setMyShopReview(mine);setShopRating(mine.rating);setShopComment(mine.comment||'')}}})();},[shopId,user]);
 useEffect(()=>{if(!productIds.length){setProductReviews([]);return}(async()=>{const{data}=await supabase.from('product_reviews').select('*').in('product_id',productIds).order('created_at',{ascending:false});setProductReviews(data||[]);if(user){const map={};(data||[]).filter(r=>r.user_id===user.id).forEach(r=>map[r.product_id]=r);setMyProductReviews(map)}})()},[productIds,user]);
 useEffect(()=>{if(!user||!shopId)return;supabase.from('shop_followers').select('id').eq('shop_id',shopId).eq('user_id',user.id).maybeSingle().then(({data})=>setFollowing(!!data))},[user,shopId]);
 const toggleFollow=async()=>{if(!user){alert('Connectez-vous pour vous abonner à cette boutique.');return}setFollowLoading(true);const q=supabase.from('shop_followers');const r=following?await q.delete().eq('shop_id',shopId).eq('user_id',user.id):await q.insert({shop_id:shopId,user_id:user.id});if(!r.error)setFollowing(!following);else alert(r.error.message);setFollowLoading(false)};
 const filtered=useMemo(()=>products.filter(p=>{const free=Number(p.price||0)===0||p.is_free===true;const promo=p.product_type==='digital'&&p.promo_price!=null&&Number(p.promo_price)<Number(p.price);if(tab==='physical')return p.product_type==='physical';if(tab==='digital')return p.product_type==='digital';if(tab==='free')return free;if(tab==='promo')return promo;return true}),[products,tab]);
 const shopAvg=shopReviews.length?shopReviews.reduce((a,r)=>a+Number(r.rating||0),0)/shopReviews.length:Number(shop?.rating||0);
 const productStats=id=>{const rs=productReviews.filter(r=>r.product_id===id);return{reviews:rs,avg:rs.length?rs.reduce((a,r)=>a+Number(r.rating||0),0)/rs.length:0}};
 const submitProductReview=async e=>{e.preventDefault();if(!user||!openProductReview)return;const p=products.find(x=>x.id===openProductReview);if(!p)return;setReviewLoading(true);const mine=myProductReviews[p.id];const payload={product_id:p.id,user_id:user.id,rating:Number(reviewRating),comment:reviewComment.trim()};const r=mine?await supabase.from('product_reviews').update({rating:payload.rating,comment:payload.comment,updated_at:new Date().toISOString()}).eq('id',mine.id).eq('user_id',user.id):await supabase.from('product_reviews').insert(payload);if(r.error)alert(r.error.message);else{const{data}=await supabase.from('product_reviews').select('*').in('product_id',productIds).order('created_at',{ascending:false});setProductReviews(data||[]);const map={};(data||[]).filter(x=>x.user_id===user.id).forEach(x=>map[x.product_id]=x);setMyProductReviews(map);setOpenProductReview(null)}setReviewLoading(false)};
 const deleteProductReview=async p=>{const mine=myProductReviews[p.id];if(!mine||!confirm('Supprimer votre avis sur ce produit ?'))return;const r=await supabase.from('product_reviews').delete().eq('id',mine.id).eq('user_id',user.id);if(r.error)alert(r.error.message);else{setProductReviews(x=>x.filter(r=>r.id!==mine.id));setMyProductReviews(x=>{const n={...x};delete n[p.id];return n})}};
 const submitShopReview=async e=>{e.preventDefault();if(!user)return;const payload={shop_id:shopId,user_id:user.id,rating:Number(shopRating),comment:shopComment.trim()};const r=myShopReview?await supabase.from('shop_reviews').update({rating:payload.rating,comment:payload.comment,updated_at:new Date().toISOString()}).eq('id',myShopReview.id).eq('user_id',user.id):await supabase.from('shop_reviews').insert(payload);if(r.error)alert(r.error.message);else{setShopReviewOpen(false);const{data}=await supabase.from('shop_reviews').select('*').eq('shop_id',shopId).order('created_at',{ascending:false});setShopReviews(data||[]);const mine=(data||[]).find(x=>x.user_id===user.id);setMyShopReview(mine||null)}};
 if(loading)return <main className="public-shop-page"><div className="public-shop-loading"><Loader2 className="spin"/>Chargement de la boutique...</div></main>;
 if(!shop)return <main className="public-shop-page"><div className="public-shop-error"><Store size={42}/><h2>Boutique introuvable</h2><button className="secondary" onClick={onBack}><ArrowLeft/>Retour</button></div></main>;
 return <main className="public-shop-page">
  <button className="secondary public-shop-back" onClick={onBack}><ArrowLeft/>Retour à la marketplace</button>
  <section className="public-shop-hero">
   <div className="public-shop-banner">{shop.banner?<img src={shop.banner} alt="Bannière"/>:<div className="public-shop-banner-empty"><ImageIcon/></div>}<div className="public-shop-logo">{shop.logo?<img src={shop.logo} alt={shop.shop_name}/>:<Store/>}</div></div>
   <div className="public-shop-info centered-shop-info"><span className="eyebrow">BOUTIQUE PJD MARKET</span><h1>{shop.shop_name}</h1><p>{shop.description||'Bienvenue dans cette boutique.'}</p><div className="public-shop-meta"><span>{shop.category||'Marketplace'}</span>{shop.city&&<span>{shop.city}{shop.country?`, ${shop.country}`:''}</span>}</div>
    <div className="public-shop-actions-row">
     <button className={`shop-follow-button ${following?'following':''}`} onClick={toggleFollow} disabled={followLoading}>{followLoading?<Loader2 size={17} className="spin"/>:following?<BellOff size={17}/>:<Bell size={17}/>} {following?'Se désabonner':"S'abonner"}</button>
     <div className="shop-stat"><Users size={18}/><strong>{Number(shop.followers_count||0).toLocaleString('fr-FR')}</strong><span>abonnés</span></div>
     <button className="shop-stat shop-stat-button" onClick={()=>{setShopReviewOpen(true);if(myShopReview){setShopRating(myShopReview.rating);setShopComment(myShopReview.comment||'')}}}><Star size={18} fill="currentColor"/><strong>{shopAvg.toFixed(1)}</strong><span>{shopReviews.length} avis</span></button>
    </div>
   </div>
  </section>
  {error&&<div className="account-message">{error}</div>}
  <section className="section public-shop-products"><div className="section-head"><div><span className="eyebrow">CATALOGUE</span><h2>Produits de {shop.shop_name}</h2><p>{products.length} produit{products.length!==1?'s':''}</p></div></div>
   <div className="product-category-tabs">{[['all','Tous',Package],['physical','Produit physique',ShoppingCart],['digital','Produit numérique',FileText],['free','Produit gratuit',Gift],['promo','Promotion',Tag]].map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={17}/>{label}</button>)}</div>
   <div className="products">{filtered.length?filtered.map(p=>{const free=Number(p.price||0)===0||p.is_free===true;const promo=p.product_type==='digital'&&p.promo_price!=null&&Number(p.promo_price)<Number(p.price);const st=productStats(p.id);const mine=myProductReviews[p.id];return <article className="product-card" key={`${p.product_type}-${p.id}`}>
    <div className="product-art">{p.display_image?<img src={p.display_image} alt={p.title} loading="lazy"/>:<Store size={54}/>}<span className={`product-type-badge ${free?'free':promo?'promo':p.product_type}`}>{free?'Produit gratuit':promo?'Promotion':p.product_type==='physical'?'Produit physique':'Produit numérique'}</span></div>
    <div className="product-body"><div className="product-cat">{p.category||'Produit'}</div><h3>{p.title}</h3><p>{p.description||''}</p><div className="product-mini-rating"><Stars value={st.avg}/><span>{st.avg?st.avg.toFixed(1):'Nouveau'} · {st.reviews.length} avis</span></div><div className="price"><strong>{money(promo?p.promo_price:p.price)}</strong>{promo&&<del>{money(p.price)}</del>}</div>
     {free&&p.file_url?<button className="add" onClick={async()=>{setDownloading(p.id);await freeDownload(p);setDownloading(null)}} disabled={downloading===p.id}><Download size={17}/>{downloading===p.id?'Téléchargement...':'Télécharger gratuitement'}</button>:<button className="add" onClick={()=>onAdd?.({...p,source_type:p.product_type})}><ShoppingCart size={17}/>Ajouter au panier</button>}
     <div className="product-review-actions"><button onClick={()=>{setOpenProductReview(p.id);setReviewRating(mine?.rating||5);setReviewComment(mine?.comment||'')}}><Star size={16}/>{mine?'Modifier mon avis':'Donner un avis'}</button>{mine&&<button onClick={()=>deleteProductReview(p)}><Trash2 size={16}/>Supprimer</button>}</div>
     {openProductReview===p.id&&<form className="product-review-form" onSubmit={submitProductReview}><strong>{mine?'Modifier votre avis':'Votre avis sur ce produit'}</strong><Stars value={reviewRating} interactive onChange={setReviewRating} size={25}/><textarea value={reviewComment} onChange={e=>setReviewComment(e.target.value)} placeholder="Votre expérience avec ce produit..." maxLength={1000} required/><div><button type="button" onClick={()=>setOpenProductReview(null)}>Annuler</button><button type="submit" disabled={reviewLoading}>{reviewLoading?<Loader2 size={16} className="spin"/>:<Send size={16}/>}Publier</button></div></form>}
    </div></article>}) : <div className="empty">Aucun produit dans cette catégorie.</div>}</div>
  </section>
  <section className="section shop-reviews-section"><div className="section-head"><div><span className="eyebrow">AVIS DE LA BOUTIQUE</span><h2>Les clients parlent de {shop.shop_name}</h2><p>{shopReviews.length} avis</p></div><button className="shop-review-button" onClick={()=>{if(!user){alert('Connectez-vous pour donner votre avis.');return}setShopReviewOpen(true)}}><Star size={17}/>{myShopReview?'Modifier mon avis':'Donner mon avis'}</button></div>
   {shopReviewOpen&&<form className="shop-review-form" onSubmit={submitShopReview}><h3>{myShopReview?'Modifier votre avis':'Donner votre avis sur la boutique'}</h3><Stars value={shopRating} interactive onChange={setShopRating} size={28}/><textarea value={shopComment} onChange={e=>setShopComment(e.target.value)} placeholder="Votre expérience avec cette boutique..." maxLength={1000} required/><div className="shop-review-form-footer"><button type="button" onClick={()=>setShopReviewOpen(false)}>Annuler</button><button type="submit" className="shop-review-submit"><Send size={17}/>Enregistrer</button></div></form>}
   <div className="shop-rating-summary"><div className="shop-rating-number"><strong>{shopAvg.toFixed(1)}</strong><Stars value={shopAvg}/><span>{shopReviews.length} avis</span></div><div className="shop-rating-text">Avis vérifiés des clients ayant acheté dans cette boutique.</div></div>
   <div className="shop-reviews-list">{shopReviews.length?shopReviews.map(r=><article className="shop-review-card" key={r.id}><div className="shop-review-head"><div className="shop-review-avatar">{String(r.user_id||'?').slice(0,1).toUpperCase()}</div><div><strong>Client</strong><Stars value={r.rating}/></div><span>{dateFr(r.created_at)}</span></div><p>{r.comment}</p></article>):<div className="empty">Aucun avis pour le moment.</div>}</div>
  </section>
 </main>
}