import React from 'react';

const items = [
  ['dashboard','🏠','Tableau de bord','dashboard'],['products','📦','Produits','products'],['add','➕','Ajouter un produit','products'],['orders','🛒','Commandes','orders'],['revenue','💰','Ventes & revenus','finance'],['stats','📊','Statistiques','dashboard'],['payments','💳','Paiements','finance'],['coupons','🎟️','Coupons','marketing'],['referral','👥','Parrainage','referral'],['messages','💬','Messages','messages'],['notifications','🔔','Notifications','notifications'],['settings','⚙️','Paramètres','settings'],['support','🆘','Aide & support','settings']
];

export default function SellerSpaceNav({ active='dashboard', onNavigate }) {
  const go=id=>onNavigate?.(id);
  const activeFor=id=>id===active||(id==='revenue'&&active==='finance');
  return <>
    <style>{`.pjd-seller-space{position:relative}.pjd-seller-space-nav>div:last-child{display:none!important}.pjd-vendor-actions{position:absolute;top:12px;right:18px;z-index:20;display:flex;gap:7px}.pjd-vendor-action{height:40px;border:1px solid #e6e7eb;background:#fff;border-radius:10px;padding:0 11px;display:flex;align-items:center;gap:7px;color:#344054;font-weight:700;cursor:pointer}.pjd-vendor-action.primary{background:#f97316;color:#fff;border-color:#f97316}.pjd-vendor-icon{font-size:17px}.pjd-vendor-label{font-size:13px}.pjd-seller-menu{width:245px;flex:0 0 245px;background:#fff;border-right:1px solid #e8e8e8;padding:16px 12px;box-sizing:border-box}.pjd-seller-menu-title{font-size:11px;font-weight:800;color:#98a2b3;text-transform:uppercase;padding:4px 10px 10px}.pjd-seller-menu-list{display:grid;gap:4px}.pjd-seller-menu button{width:100%;border:0;background:transparent;text-align:left;padding:11px 12px;border-radius:10px;cursor:pointer;font-size:14px;color:#555;display:flex;align-items:center;gap:10px}.pjd-seller-menu button.active{background:#fff1e8;color:#ea580c;font-weight:700}.pjd-seller-menu .icon{width:23px;text-align:center}.pjd-seller-mobile{display:none}@media(max-width:800px){.pjd-vendor-actions{top:62px;right:10px;gap:5px}.pjd-vendor-action{width:38px;padding:0;justify-content:center}.pjd-vendor-label{display:none}.pjd-seller-menu{display:none}.pjd-seller-mobile{position:fixed;display:grid;grid-template-columns:repeat(5,1fr);left:0;right:0;bottom:0;height:64px;background:#fff;border-top:1px solid #ddd;z-index:1000}.pjd-seller-mobile button{border:0;background:transparent;color:#667085;font-size:10px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px}.pjd-seller-mobile button.active{color:#ea580c;font-weight:800}.pjd-seller-mobile .micon{font-size:19px}.seller-space-content{padding-bottom:78px!important}}`}</style>
    <div className="pjd-vendor-actions">
      <button className="pjd-vendor-action primary" onClick={()=>go('products')} title="Ajouter un produit"><span className="pjd-vendor-icon">➕</span><span className="pjd-vendor-label">Ajouter un produit</span></button>
      <button className="pjd-vendor-action" onClick={()=>go('notifications')} title="Notifications"><span className="pjd-vendor-icon">🔔</span><span className="pjd-vendor-label">Notifications</span></button>
      <button className="pjd-vendor-action" onClick={()=>go('messages')} title="Messages"><span className="pjd-vendor-icon">💬</span><span className="pjd-vendor-label">Messages</span></button>
      <button className="pjd-vendor-action" onClick={()=>go('orders')} title="Commandes"><span className="pjd-vendor-icon">📦</span><span className="pjd-vendor-label">Commandes</span></button>
      <button className="pjd-vendor-action" onClick={()=>go('settings')} title="Profil vendeur"><span className="pjd-vendor-icon">👤</span><span className="pjd-vendor-label">Profil</span></button>
    </div>
    <aside className="pjd-seller-menu"><div className="pjd-seller-menu-title">Menu vendeur</div><nav className="pjd-seller-menu-list">{items.map(([id,icon,label,target])=><button key={id} className={activeFor(id)?'active':''} onClick={()=>go(target)}><span className="icon">{icon}</span><span>{label}</span></button>)}</nav></aside>
    <nav className="pjd-seller-mobile">{[['dashboard','🏠','Accueil'],['products','📦','Produits'],['orders','🛒','Commandes'],['finance','💰','Revenus'],['settings','👤','Profil']].map(([id,icon,label])=><button key={id} className={active===id?'active':''} onClick={()=>go(id)}><span className="micon">{icon}</span>{label}</button>)}</nav>
  </>;
}
