import React,{useEffect,useMemo,useState}from'react';
import{supabase}from'./lib/supabase';
import{PackagePlus,Upload,FileText,Image as ImageIcon,Video,Music,Archive,BookOpen,Loader2,X,CheckCircle2,Boxes,TrendingUp,ShoppingBag,Wallet,Percent,Save,BarChart3}from'lucide-react';
import'./seller.css';

const categories=['Applications & APK','E-books & PDF','Formations','Design & Création','Templates','Documents','Mode','Électronique','Maison','Beauté','Alimentation','Services','Musique & Audio','Vidéos','Photos & Images','Autres'];
const iconFor=t=>{if(t?.startsWith('video/'))return Video;if(t?.startsWith('audio/'))return Music;if(t?.startsWith('image/'))return ImageIcon;if(t?.includes('zip')||t?.includes('rar'))return Archive;if(t?.includes('pdf')||t?.includes('epub'))return BookOpen;return FileText};
const money=v=>`${Number(v||0).toLocaleString('fr-FR')} FCFA`;
const imageOf=p=>p?.cover_image||p?.image_url||(Array.isArray(p?.images)?p.images[0]:typeof p?.images==='string'?p.images:null)||null;

export default function SellerDashboard({session,shop,activeTab='dashboard',onBack}){
 const[tab,setTab]=useState(activeTab),[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[priceEdits,setPriceEdits]=useState({});
 const[title,setTitle]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState('E-books & PDF'),[price,setPrice]=useState(''),[free,setFree]=useState(false),[stock,setStock]=useState('0'),[sku,setSku]=useState(''),[file,setFile]=useState(null),[cover,setCover]=useState(null),[imageUrl,setImageUrl]=useState('');
 useEffect(()=>setTab(activeTab||'dashboard'),[activeTab]);
 useEffect(()=>{if(session?.user?.id)loadData()},[session?.user?.id]);
 async function loadData(){
  if(!session?.user?.id)return;setLoading(true);setMessage('');
  try{
   const uid=session.user.id;
   const [d,m,oi]=await Promise.all([
    supabase.from('digital_products').select('*').eq('seller_id',uid).order('created_at',{ascending:false}),
    supabase.from('marketplace_products').select('*').eq('seller_id',uid).order('created_at',{ascending:false}),
    supabase.from('order_items').select('order_id,name,price,unit_price,line_total,quantity,commission,seller_net,shop_id').eq('seller_id',uid)
   ]);
   const err=[d,m,oi].find(x=>x.error)?.error;if(err)throw err;
   const digital=(d.data||[]).map(p=>({...p,product_type:'digital',display_image:imageOf(p)}));
   const physical=(m.data||[]).map(p=>({...p,product_type:'physical',display_image:imageOf(p)}));
   setProducts([...digital,...physical]);
   const ids=[...new Set((oi.data||[]).map(x=>x.order_id).filter(Boolean))];
   if(ids.length){const r=await supabase.from('orders').select('id,status,total,created_at,user_id').in('id',ids);if(r.error)throw r.error;setOrders((r.data||[]).map(o=>({...o,items:(oi.data||[]).filter(x=>x.order_id===o.id)})))}else setOrders([]);
  }catch(e){setMessage(e.message||'Impossible de charger les données du vendeur.');setProducts([]);setOrders([])}finally{setLoading(false)}
 }
 function reset(){setTitle('');setDescription('');setCategory('E-books & PDF');setPrice('');setFree(false);setStock('0');setSku('');setFile(null);setCover(null);setImageUrl('')}
 async function uploadDigital(){
  if(!session?.user?.id||!shop?.id)return setMessage('Votre boutique doit être active avant de publier.');
  if(!title.trim())return setMessage('Indiquez le nom du produit.');
  if(!file)return setMessage('Sélectionnez le fichier à vendre.');
  if(!free&&(!price||Number(price)<0))return setMessage('Indiquez un prix ou activez « Gratuit ».');
  setSaving(true);setMessage('');
  const safe=(file.name||'fichier').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'_');
  const path=`${session.user.id}/${shop.id}/${Date.now()}-${safe}`;
  const up=await supabase.storage.from('product-files').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream',cacheControl:'3600'});
  if(up.error){setMessage(`Import du fichier impossible : ${up.error.message}`);setSaving(false);return}
  let coverUrl=null;
  if(cover){const ext=(cover.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase()||'jpg';const cp=`${session.user.id}/${shop.id}/cover-${Date.now()}.${ext}`;const cu=await supabase.storage.from('public-assets').upload(cp,cover,{upsert:false,contentType:cover.type,cacheControl:'3600'});if(cu.error){await supabase.storage.from('product-files').remove([path]);setMessage(`Couverture impossible : ${cu.error.message}`);setSaving(false);return}coverUrl=supabase.storage.from('public-assets').getPublicUrl(cp).data?.publicUrl||null}
  const payload={seller_id:session.user.id,shop_id:shop.id,title:title.trim(),description:description.trim(),category,price:free?0:Number(price||0),promo_price:null,stock:Math.max(0,Number(stock)||0),sku:sku.trim()||null,file_url:path,file_type:file.type||null,image_url:coverUrl||imageUrl||null,cover_image:coverUrl||imageUrl||null,is_free:free,status:'actif',source_type:'digital'};
  const r=await supabase.from('digital_products').insert(payload).select().single();
  if(r.error){await supabase.storage.from('product-files').remove([path]);setMessage(`Produit non créé : ${r.error.message}`);setSaving(false);return}
  setMessage('Produit numérique publié avec son image.');reset();await loadData();setSaving(false)
 }
 async function savePrice(p){
  const edit=priceEdits[p.product_type+':'+p.id]||{};const nextPrice=Number(edit.price);const nextPromo=edit.promo===''||edit.promo==null?null:Number(edit.promo);
  if(!Number.isFinite(nextPrice)||nextPrice<0)return setMessage('Prix invalide.');
  if(nextPromo!=null&&(!Number.isFinite(nextPromo)||nextPromo<0||nextPromo>=nextPrice))return setMessage('Le prix promotionnel doit être inférieur au prix normal.');
  setSaving(true);setMessage('');
  const payload=p.product_type==='digital'?{price:nextPrice,promo_price:nextPromo,is_free:nextPrice===0}:{price:nextPrice};
  const r=await supabase.from(p.product_type==='digital'?'digital_products':'marketplace_products').update(payload).eq('id',p.id).eq('seller_id',session.user.id);
  if(r.error)setMessage(`Prix non enregistré : ${r.error.message}`);else{setMessage('Prix enregistré.');await loadData()};setSaving(false)
 }
 const stats=useMemo(()=>{const valid=orders.filter(o=>!['cancelled','canceled','refunded'].includes(String(o.status||'').toLowerCase()));const revenue=valid.reduce((s,o)=>s+Number(o.items?.reduce((a,i)=>a+Number(i.line_total??(Number(i.unit_price??i.price||0)*Number(i.quantity||1))),0)||0),0);const commission=valid.reduce((s,o)=>s+Number(o.items?.reduce((a,i)=>a+Number(i.commission||0),0)||0),0);const net=valid.reduce((s,o)=>s+Number(o.items?.reduce((a,i)=>a+Number(i.seller_net??(Number(i.line_total??0)-Number(i.commission||0))),0)||0),0);const units=valid.reduce((s,o)=>s+Number(o.items?.reduce((a,i)=>a+Number(i.quantity||1),0)||0),0);const days=[];for(let n=6;n>=0;n--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-n);const key=d.toISOString().slice(0,10);days.push({key,label:d.toLocaleDateString('fr-FR',{weekday:'short'}),value:valid.filter(o=>String(o.created_at||'').slice(0,10)===key).reduce((s,o)=>s+Number(o.items?.reduce((a,i)=>a+Number(i.line_total??0),0)||0),0)})}const top={};valid.flatMap(o=>o.items||[]).forEach(i=>{const k=i.name||'Produit';top[k]=(top[k]||0)+Number(i.line_total??0)});const topList=Object.entries(top).sort((a,b)=>b[1]-a[1]).slice(0,5);return{revenue,commission,net,units,orders:valid.length,avg:valid.length?revenue/valid.length:0,days,topList}},[orders]);
 const lowStock=products.filter(p=>Number(p.stock||0)<=5).length;
 const editFor=p=>priceEdits[p.product_type+':'+p.id]||{price:String(p.price??0),promo:p.product_type==='digital'&&p.promo_price!=null?String(p.promo_price):''};
 if(tab==='dashboard')return <Dashboard stats={stats} products={products} lowStock={lowStock} loading={loading} onRefresh={loadData}/>;
 if(tab==='finance')return <Finance stats={stats} loading={loading}/>;
 if(tab==='stock')return <Stock products={products} loading={loading} lowStock={lowStock}/>;
 if(tab!=='products')return <div className="seller-card wide-card"><div className="page-title"><div><span className="eyebrow">ESPACE VENDEUR</span><h2>{tab==='settings'?'Paramètres vendeur':'Produits & gestion du stock'}</h2><p>{tab==='settings'?'Les paramètres de la boutique sont disponibles dans « Ma boutique ».':'Ajoutez et gérez vos produits physiques ou numériques.'}</p></div><Boxes size={34}/></div><button className="primary" onClick={()=>setTab('products')}>Gérer les produits</button></div>;
 return <div className="seller-card wide-card"><div className="page-title"><div><span className="eyebrow">CATALOGUE</span><h2>Produits & gestion des prix</h2><p>Les images, prix et prix promotionnels sont configurables directement ici.</p></div><PackagePlus size={34}/></div>
  <div className="digital-import-card"><div className="digital-import-head"><Upload/><div><h3>Importer un fichier à vendre</h3><p>Le fichier original est conservé dans le stockage privé PJD Maker.</p></div></div>
   <div className="form-grid"><label>Nom du produit<input value={title}onChange={e=>setTitle(e.target.value)}placeholder="Ex. Mon e-book"/></label><label>Catégorie<select value={category}onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="full-label">Description<textarea rows="4" value={description}onChange={e=>setDescription(e.target.value)}placeholder="Décrivez le contenu du fichier..."/></label><label>Prix (FCFA)<input type="number" min="0" value={price}disabled={free}onChange={e=>setPrice(e.target.value)}/></label><label className="dpu-free"><input type="checkbox" checked={free}onChange={e=>setFree(e.target.checked)}/> Produit gratuit</label><label>Stock<input type="number" min="0" value={stock}onChange={e=>setStock(e.target.value)}/></label><label>SKU<input value={sku}onChange={e=>setSku(e.target.value)}placeholder="Optionnel"/></label></div>
   <label className="dpu-file"><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/>{React.createElement(iconFor(file?.type),{size:32})}<div><strong>{file?file.name:'Sélectionner le fichier à vendre'}</strong><small>{file?`${(file.size/1024/1024).toFixed(2)} Mo · ${file.type||'fichier'}`:'PDF · e-book · vidéo · audio · photo · ZIP · APK · autres'}</small></div><Upload size={20}/></label>
   <label className="dpu-cover"><input type="file" accept="image/*" onChange={e=>setCover(e.target.files?.[0]||null)}/><ImageIcon size={20}/><span>{cover?cover.name:'Ajouter une couverture / miniature (facultatif)'}</span></label>
   {message&&<div className="seller-message"><CheckCircle2 size={17}/>{message}<button onClick={()=>setMessage('')}><X size={15}/></button></div>}
   <button className="primary" onClick={uploadDigital} disabled={saving}>{saving?<><Loader2 className="spin"/> Importation...</>:<><Upload size={17}/> Publier et vendre</>}</button>
  </div>
  <div className="seller-card-title"><Boxes/><div><h3>Catalogue et configuration des prix</h3><p>{loading?'Chargement...':`${products.length} produit(s)`}</p></div></div>
  <div style={{display:'grid',gap:12}}>{products.map(p=>{const e=editFor(p);return <div key={p.product_type+':'+p.id} style={{display:'grid',gridTemplateColumns:'72px minmax(0,1fr) auto',gap:14,alignItems:'center',border:'1px solid #e5e7eb',borderRadius:14,padding:12,background:'#fff'}}><div style={{width:72,height:72,borderRadius:10,overflow:'hidden',background:'#f2f3f5',display:'grid',placeItems:'center'}}>{p.display_image?<img src={p.display_image} alt={p.title||''} style={{width:'100%',height:'100%',objectFit:'cover'}} onError={ev=>{ev.currentTarget.style.display='none'}}/>:<ImageIcon size={25}/>}</div><div style={{minWidth:0}}><b style={{display:'block',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{p.title}</b><small>{p.product_type==='digital'?'Numérique':'Physique'} · stock {Number(p.stock||0)}</small><div style={{display:'flex',gap:8,marginTop:7,flexWrap:'wrap'}}><input type="number" min="0" value={e.price} onChange={ev=>setPriceEdits(x=>({...x,[p.product_type+':'+p.id]:{...e,price:ev.target.value}}))} style={{width:125,padding:8,border:'1px solid #d8dce1',borderRadius:8}} placeholder="Prix"/>{p.product_type==='digital'&&<input type="number" min="0" value={e.promo} onChange={ev=>setPriceEdits(x=>({...x,[p.product_type+':'+p.id]:{...e,promo:ev.target.value}}))} style={{width:125,padding:8,border:'1px solid #d8dce1',borderRadius:8}} placeholder="Promo"/>}</div></div><button className="primary" disabled={saving} onClick={()=>savePrice(p)}><Save size={16}/> Enregistrer</button></div>})}</div>
 </div>
}
function Dashboard({stats,products,lowStock,loading,onRefresh}){const max=Math.max(1,...stats.days.map(d=>d.value));return <div className="seller-card wide-card"><div className="page-title"><div><span className="eyebrow">TABLEAU DE BORD</span><h2>Analyse de votre activité</h2><p>Chiffre d'affaires, commandes, commissions, ventes et produits.</p></div><button className="primary" onClick={onRefresh}><BarChart3 size={17}/> Actualiser</button></div>{loading?<div className="seller-message">Chargement des analyses...</div>:<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12}}>{[['CA',stats.revenue,TrendingUp],['Commandes',stats.orders,ShoppingBag],['Panier moyen',stats.avg,BarChart3],['Net vendeur',stats.net,Wallet],['Commission',stats.commission,Percent],['Unités vendues',stats.units,PackagePlus]].map(([l,v,I])=><div key={l} style={{padding:16,border:'1px solid #e5e7eb',borderRadius:14,background:'#fff'}}><I size={18}/><small style={{display:'block',color:'#667085',marginTop:8}}>{l}</small><strong style={{display:'block',fontSize:22,marginTop:4}}>{l==='Commandes'||l==='Unités vendues'?Number(v).toLocaleString('fr-FR'):money(v)}</strong></div>)}</div><div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(250px,1fr)',gap:14,marginTop:16}}><section style={{border:'1px solid #e5e7eb',borderRadius:14,padding:16,background:'#fff'}}><h3>Ventes des 7 derniers jours</h3><div style={{display:'flex',alignItems:'end',gap:8,height:150}}>{stats.days.map(d=><div key={d.key} style={{flex:1,textAlign:'center'}}><div title={money(d.value)} style={{height:`${Math.max(6,(d.value/max)*110)}px`,background:'#151515',borderRadius:'6px 6px 2px 2px'}}/><small>{d.label}</small></div>)}</div></section><section style={{border:'1px solid #e5e7eb',borderRadius:14,padding:16,background:'#fff'}}><h3>Meilleurs produits</h3>{stats.topList.length?stats.topList.map(([n,v])=><div key={n} style={{display:'flex',justifyContent:'space-between',gap:8,padding:'9px 0',borderBottom:'1px solid #eee'}}><span style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{n}</span><b>{money(v)}</b></div>):<p>Aucune vente enregistrée.</p>}</section></div><div style={{marginTop:14,padding:14,borderRadius:12,background:lowStock?'#fff7ed':'#f5f7fa'}}><b>{lowStock?`⚠️ ${lowStock} produit(s) avec stock faible`:'✓ Stock sans alerte'}</b><span style={{marginLeft:8,color:'#667085'}}>{products.length} produit(s) au catalogue.</span></div></>}</div>}
function Finance({stats,loading}){return <div className="seller-card wide-card"><div className="page-title"><div><span className="eyebrow">FINANCES</span><h2>Analyse financière</h2><p>Vue claire du chiffre d'affaires, des commissions et du revenu net.</p></div><Wallet size={34}/></div>{loading?<div className="seller-message">Chargement...</div>:<div style={{display:'grid',gap:12}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}>{[['Chiffre d’affaires',stats.revenue],['Commissions PJD',stats.commission],['Revenu net',stats.net],['Panier moyen',stats.avg]].map(([l,v])=><div key={l} style={{padding:18,border:'1px solid #e5e7eb',borderRadius:14}}><small>{l}</small><h2 style={{margin:'6px 0 0'}}>{money(v)}</h2></div>)}</div><p style={{color:'#667085'}}>Les montants sont calculés à partir des commandes et articles réellement associés à votre compte vendeur.</p></div>}</div>}
function Stock({products,loading,lowStock}){return <div className="seller-card wide-card"><div className="page-title"><div><span className="eyebrow">STOCK</span><h2>Gestion du stock</h2><p>{lowStock} produit(s) à surveiller.</p></div><Boxes size={34}/></div>{loading?<div className="seller-message">Chargement...</div>:<div style={{display:'grid',gap:8}}>{products.map(p=><div key={p.product_type+':'+p.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:13,border:'1px solid #e5e7eb',borderRadius:11}}><span>{p.title}</span><b>{Number(p.stock||0)} unité(s)</b></div>)}</div>}</div>}
